[BE] C++20 template instantiation adjustments (#168132)
Resolve some dependent name disambiguation issues, which results in compilation errors when compiled with MSVC using C++20 standard. Failure look something like the following
```
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\cuda\Nonzero.cu(215): error: type name is not allowed
        (void*)pinned_num_nonzeros_h.const_data_ptr<int>(),
                                                    ^

C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\cuda\Nonzero.cu(215): error: expected an expression
        (void*)pinned_num_nonzeros_h.const_data_ptr<int>(),
                                                         ^
```
And resolved by adding a `template` in front of it

The only C++20 specific change in the [standard](https://en.cppreference.com/w/cpp/language/dependent_name.html) that I can spot are the following:
> The following expressions are type-dependent ﻿:
> - an expression whose any subexpression is a type-dependent expression this, if the class is a dependent type.
> - an [identifier expression](https://en.cppreference.com/w/cpp/language/name.html) that is not a [concept-id](https://en.cppreference.com/w/cpp/language/constraints.html) and(since C++20)
> - contains an identifier for which name lookup finds at least one dependent declaration
> - contains a dependent [template-id](https://en.cppreference.com/w/cpp/language/templates.html#template-id)

Also replace `*((int*)ptr + offs)` with `static_cast<int *>(ptr)[offs]`
Pull Request resolved: https://github.com/pytorch/pytorch/pull/168132
Approved by: https://github.com/ngimel, https://github.com/Skylion007, https://github.com/cyyever
ghstack dependencies: #168165