[ROCm] Resolve build issue due to flatbuffers version (#173555)
When building PyTorch with the latest 7.11.0 ROCm tarballs (not wheels), the ROCm SDK headers in /opt/rocm-7.11.0/include were being searched before PyTorch's vendored third-party headers. This caused build failures when ROCm ships newer versions of libraries than what PyTorch's generated code expects (e.g., flatbuffers 25.x vs 24.x).

Error snippet:
```
In file included from /app/pytorch/torch/csrc/jit/mobile/flatbuffer_loader.cpp:55:
/app/pytorch/torch/csrc/jit/serialization/mobile_bytecode_generated.h:11:41: error: static assertion failed: Non-compatible flatbuffers version included
   11 | static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
```
New rocm include headers location:
```
    40  -I/app/pytorch/build/third_party/onnx
    41  -I/app/pytorch/third_party/flatbuffers/include
    42  -isystem /opt/rocm-7.11.0/include
    43  -isystem /app/pytorch/build/third_party/gloo
    44  -isystem /app/pytorch/cmake/../third_party/gloo
```

Old:
```
I/app/pytorch/build -I/app/pytorch -I/opt/rocm-7.11.0/include
...
I/app/pytorch/third_party/flatbuffers/include -isystem
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/173555
Approved by: https://github.com/jeffdaily