Add missing TORCH_API annotation
Without it I get

```
ImportError: /data/users/ezyang/pytorch-tmp/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch3jit18checkDoubleInRangeEd
```

when I build with DEBUG=1

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

[ghstack-poisoned]