Skip `test_tma_stable_reconstruct` on Python 3.13+ (#189712)
In Python 3.12 and lower the `__eq__` of the (Tritons) `TensorDescriptor` skipped the actual comparison of the tensor when it was the same instance. In newer Python versions default comparison is performed which yields a bool-tensor that is then contextually converted to `bool` which fails with
> RuntimeError: Boolean value of Tensor with more than one value is ambiguous

This skips the test introduced in https://github.com/pytorch/pytorch/pull/155662 to unblock Python 3.13

I guess a generic solution could be in `originate_pairs` to convert any dataclass to a tuple first using `dataclasses.totuple`

Pull Request resolved: https://github.com/pytorch/pytorch/pull/189712
Approved by: https://github.com/albanD