Refine reusable event usage scope on XPUEvent (#197396)
# Motivation
Without this PR, we enable reusable events on BMG+. However, we encounter the `host_task` limitation in oneCCL, which uses `host_task` in `onecclGroupEnd` resulting in an error on BMG with compiler 2026.2:
```bash
RuntimeError: An event cannot be enqueued for signaling or waiting behind a command which is not enqueued in the backend.

```
With this PR, we only enable reusable events when IPC is enabled, avoiding the `host_task` limitation in the non-IPC case.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/197396
Approved by: https://github.com/gujinghui