Resolve one odd failure on Python 2.7 related to exec() scope
Most py27 CI builds passed, but one failed with:
```
SyntaxError: unqualified exec is not allowed in function 'decorator' it
is a nested function (_overrides.py, line 231)
```

This is https://bugs.python.org/issue21591, which was fixed in
Python 2.7.9, looks like
`caffe2-py2-devtoolset7-rocmrpm-centos7.5-test` uses an older version.