Cherrypick MTIA chagne to llama4-flagship branch
Summary: Need to cherry pick this change, otherwise it's failing build.

Test Plan:
  ~/local/llm/pytorch (xdwang_kineto_update)]$ with_proxy python setup.py develop

Before:
```
/data/users/xdwang/llm/pytorch/torch/csrc/profiler/kineto_shim.cpp:53:30: error: 'MTIA_WORKLOADD' is not a member of 'libkineto::ActivityType'
   53 |     libkineto::ActivityType::MTIA_WORKLOADD,
      |                              ^~~~~~~~~~~~~~
/data/users/xdwang/llm/pytorch/torch/csrc/profiler/kineto_shim.cpp:54:1: error: could not convert '{libkineto::ActivityType::MTIA_CCP_EVENTS, libkineto::ActivityType::MTIA_RUNTIME, <expression error>}' from '<brace-enclosed initializer list>' to 'const std::set<libkineto::ActivityType>'
   54 | };
      | ^
      | |
      | <brace-enclosed initializer list>
/data/users/xdwang/llm/pytorch/torch/csrc/profiler/kineto_shim.cpp: In function 'c10::DeviceType torch::autograd::profiler::deviceTypeFromActivity(libkineto::ActivityType)':
/data/users/xdwang/llm/pytorch/torch/csrc/profiler/kineto_shim.cpp:396:35: error: 'MTIA_WORKLOADD' is not a member of 'libkineto::ActivityType'
  396 |     case libkineto::ActivityType::MTIA_WORKLOADD: {
      |                                   ^~~~~~~~~~~~~~

```
After: 
```
Finished processing dependencies for torch==2.8.0a0+gitce1f9b6
```

Rollback Plan: 

Reviewers: sraikund

Reviewed By: sraikund

Subscribers: pramacha, zhuoran, yoyoyod, qizixi, quanxili, yings

Differential Revision: https://phabricator.intern.facebook.com/D77921825