Use MKL_INT in MKL wrapper interfaces (#118734)
I encountered the error when built PyTorch on Windows MKL:

```
pytorch\aten\src\ATen\native\mkl\LinearAlgebra.cpp(74): error C2664: “void cblas_sgemm_batch(const CBLAS_LAYOUT,const CBLAS_TRANSPOSE *,const CBLAS_TRANSPOSE *,const __int64 *,const __int64 *,const __int64 *,const float *,const float **,const __int64 *,const float **,const __int64 *,const float *,float **,const __int64 *,const __int64,const __int64 *) noexcept”: 无法将参数 4 从“const int *”转换为“const __int64 *”
pytorch\aten\src\ATen\native\mkl\LinearAlgebra.cpp(74): note: 指向的类型不相关; 转换需要 reinterpret_cast、C 样式强制转换或带圆括号的函数样式强制转换
C:\Program Files (x86)\Intel\oneAPI\2024.0\include\mkl_cblas.h(550): note: 参见“cblas_sgemm_batch”的声明
```
This was because MKL_INT was defined as int64_t. This PR tries to use MKL_INT.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/118734
Approved by: https://github.com/ezyang