[ATen-VK] Resolve compiler_flags to allow Mac build (#125361)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/125361

## `-Wmissing-prototypes`

In ATen-Vulkan, we often define functions in `.cpp` files without declaring them in `.h` files without hiding them in an anonymous namespace.

Example: [`Packing.cpp`'s channel_image_repacking()](https://github.com/pytorch/pytorch/blob/f1f142c44f81384afbdba5e451fc15744868bf26/aten/src/ATen/native/vulkan/impl/Packing.cpp#L299-L348)
```
xplat/caffe2/aten/src/ATen/native/vulkan/impl/Packing.cpp:299:9: error: no previous prototype for function 'channel_image_repacking' [-Werror,-Wmissing-prototypes]
vTensor channel_image_repacking(
        ^
```

On Mac, this results in a `-Wmissing-prototypes` warning, which is disabled in this change.

## `-Wshadow`

In `Adapter.cpp`, we overwrite a variable called `properties`, which we fix in this change as opposed to disabling the warning.

Test Plan: CI

Differential Revision: D56850324