[modcmake 2/N] Switch ATen target_link_libraries to new-style syntax
Modern CMake uses target_link_libraries with PUBLIC/PRIVATE keywords
to specify how a library works.  This can matter quite a bit when
you are linking against a static versus a dynamic library: if you are
creating a dynamical library, it is a bad idea to link a static
library to it PUBLICally, as every downstream consumer will attempt
to redundantly link that static library along with your dynamic
library (which is also exporting those static library symbols.)  This
manifested itself as a very weird error where linking verify_api_visibility
would lead to the message:

    /opt/conda/lib/libmkl_gf_lp64.so: undefined reference to `mkl_lapack_zgbtrf'

Even though everything else is in order.  Don't do that.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>