Fix warnings issue in test_tensor_with_grad_to_scalar_warning (#2386)
This PR is to cherry-pick test_torch.py changes from upstream
[22d1359](https://github.com/pytorch/pytorch/commit/22d1359bc6b2316ee77ee134bfb258b4fa9ab643).

This fixes the below error:
```
_____________________________________________________________________________ TestTorch.test_tensor_with_grad_to_scalar_warning ______________________________________________________________________________
Traceback (most recent call last):
  File "/root/PR/pytorch/test/test_torch.py", line 10849, in test_tensor_with_grad_to_scalar_warning
    self.assertEqual(len(w), 1)
  File "/opt/venv/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4114, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 1 but got 2.
Absolute difference: 1
Relative difference: 1.0

To execute this test, run the following from the base repo dir:
    python test/test_torch.py TestTorch.test_tensor_with_grad_to_scalar_warning

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

This fixes https://ontrack-internal.amd.com/browse/SWDEV-532432