Fix missing ConstantPooling header in passes.cpp (#169420)
Summary:
The previous diff (D88000002) removed the `constant_pooling.h` header from `/data/users/wouterdevriendt/fbsource/xplat/caffe2/torch/csrc/jit/runtime/static/passes.cpp`, but the file still uses the `ConstantPooling` function in the `SplitOutPrecomputeOpsForSparseNN` function. This caused a compilation error:

```
error: use of undeclared identifier 'ConstantPooling'
```

This diff adds back the necessary header to fix the compilation error.

Test Plan:
Buck build should now pass:
```
buck2 build fbcode//caffe2:_libtorch --mode=opt
```

Differential Revision: D88060085

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169420
Approved by: https://github.com/yangw-dev, https://github.com/atalman, https://github.com/cyyever