[Inductor] Remove ReinterpretView from all layout constraint considerations (#179283) (#179283)
Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/179283

Test Plan: test_deferred_layout_constraint_reinterpret_3d

`ReinterpretView` should just return the direct stride from get_stride_and_maybe_freeze_layout, instead of looking at the underlying buffer. This causes issues such as:

```
"select_algorithm.py", line 851, in stride
    return texpr(self.rename_indexing(val[index]))
                                      ~~~^^^^^^^
torch._inductor.exc.InductorError: LoweringException: IndexError: list index out of range
  target: aten.bmm.default
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='permute_140', layout=FixedLayout('cuda:0', torch.bfloat16, size=[bs, 128, 1053], stride=[117952, 1, 112]))
  ))
  args[1]: TensorBox(
    ReinterpretView(
      StorageBox(
        ComputedBuffer(name='buf500', layout=FlexibleLayout('cuda:0', torch.bfloat16, size=[bs, 42120], stride=[42176, 1]), data=Pointwise(
          'cuda',
```

Differential Revision: D99470427

Pull Request resolved: https://github.com/pytorch/pytorch/pull/179283
Approved by: https://github.com/warrendeng