Update on "Raise TypeErrors if Tensor cannot be cast to scalar"
From Python documentation on [built-in exceptions](https://docs.python.org/3/library/exceptions.html#TypeError):
> Passing arguments of the wrong type (e.g. passing a [list](https://docs.python.org/3/library/stdtypes.html#list) when an [int](https://docs.python.org/3/library/functions.html#int) is expected) should result in a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError), but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError)


which should result in the following behavior:
```python
>>> float(torch.tensor([1, 2]))
TypeError: only one element tensors can be converted to Python scalars
>>> torch.tensor([1,2]).item()
TypeError: a Tensor with 2 elements cannot be converted to Scalar
>>> float(torch.tensor(1.5j))
ValueError: value cannot be converted to type double without overflow
```

Tested by:
 -  `test_errors_masked_fill` and `test_errors_item` in `test_ops` 
 -  `test_interpolate_undefined_behavior_casting` in `test_nn.py`
 -  `test__complex__should_not_work` in `numpy_tests/core/test_multiarray.py` 
 -  `test_simple_scalar_cast` and `test_randperm` in `test_tensor_creation_ops.py`
 - `test_pointwise_op_with_tensor_of_scalarlist_overload` in `test_foreach.py`
 -  [`aten/src/ATen/test/scalar_test.cpp`](https://github.com/pytorch/pytorch/blob/261cae793a19d91fda0d44d2c2bd8cd7e9a0b93f/aten/src/ATen/test/scalar_test.cpp#L58)

Fixes https://github.com/pytorch/pytorch/issues/110605

[ghstack-poisoned]