allow models loaded from disk with nn.LogSoftmax or nn.Softmax layers to be exported to onnx
Summary:
nn.Module sets a few base properties in its __setstate__ method which the onnx exporter apparently needs.

Currently trying to load a saved model from disk and then export that model to onnx fails with:
`AttributeError: 'LogSoftmax' object has no attribute '_state_dict_hooks'`

Very easy to fix, just need to call nn.Module's __setstate__ method to make sure the core state members get set up.

Differential Revision: D12983011

fbshipit-source-id: b2d2ad3df9c3869ca58968cae0922c2937a7fa54