Add const modifier for lazy shape inference for boolean logic ops (#79999)
Follow up to https://github.com/pytorch/pytorch/pull/78004.

---

Trying to fully codegen these boolean logic ops on pt/xla's side, saw errors:
```
Exception: Missing shape inference function.

Please add declare this function in /workspace/pytorch/torch/csrc/lazy/core/shape_inference.h:

and implement it in the the corresponding shape_inference.cpp file.

TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_and(const at::Tensor & self, const at::Tensor & other);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_not(const at::Tensor & self);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_or(const at::Tensor & self, const at::Tensor & other);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_xor(const at::Tensor & self, const at::Tensor & other);
Failed to generate lazy files: ['python', '/workspace/pytorch/xla/scripts/gen_lazy_tensor.py']
```

Add const modifier for lazy shape inference for boolean logic ops
Pull Request resolved: https://github.com/pytorch/pytorch/pull/79999
Approved by: https://github.com/wconstab