Catch runtime use of ROCm gpus that were not built
The gpus built for are a subset of the possible runtime gpus.
For example when

PYTORCH_ROCM_ARCH="gfx1030;gfx1100;gfx1101"

Is used on system with an gfx1100 and gfx1036, when this is run
import torch
for i in range(torch.cuda.device_count()):
   print(torch.cuda.get_device_properties(i).name)
   print(torch.cuda.get_device_properties(i))

This is the result.

AMD Radeon Pro W7900
_CudaDeviceProperties(name='AMD Radeon Pro W7900', major=11, minor=0, gcnArchName='gfx1100', total_memory=46064MB, multi_processor_count=48, uuid=64323261-6439-6132-3830-363533343633, L2_cache_size=6MB)
AMD Radeon Graphics
_CudaDeviceProperties(name='AMD Radeon Graphics', major=10, minor=3, gcnArchName='gfx1036', total_memory=512MB, multi_processor_count=1, uuid=58580000-0000-0000-0000-000000000000, L2_cache_size=0MB)

gfx1036 is an APU, so a common option.

Without a runtime check, when the use sets the device to gfx1036, it fail somewhere in the interior
as something spits out a crypric message.

Now with a runtime check, this

import torch
for i in range(torch.cuda.device_count()):
   print(torch.cuda.get_device_properties(i).name)
   print(torch.cuda.get_device_properties(i))
   torch.cuda.set_device(i)

Produces

AMD Radeon Pro W7900
_CudaDeviceProperties(name='AMD Radeon Pro W7900', major=11, minor=0, gcnArchName='gfx1100', total_memory=46064MB, multi_processor_count=48, uuid=64323261-6439-6132-3830-363533343633, L2_cache_size=6MB)
AMD Radeon Graphics
_CudaDeviceProperties(name='AMD Radeon Graphics', major=10, minor=3, gcnArchName='gfx1036', total_memory=512MB, multi_processor_count=1, uuid=58580000-0000-0000-0000-000000000000, L2_cache_size=0MB)
Traceback (most recent call last):
  File ".../set_device.py", line 5, in <module>
    torch.cuda.set_device(i)
  File ".../.local/lib/python3.12/site-packages/torch/cuda/__init__.py", line 477, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: unbuilt gpu used to SetDevice

Signed-off-by: Tom Rix <Tom.Rix@amd.com>