[Inductor] Don't always strip compute-capability suffix (#187888)
Following #185328 tests such as

```
File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
torch._inductor.exc.InductorError: CalledProcessError: Command '['nvcc', '-fatbin', '/tmp/tmpri_861ie/ce75deix5v2ltuxilvqvbxmlr5qvlqmr22yvpthfi2chjjhlxkcn/cos_triton_poi_fused_cos_0.ptx', '-o', '/tmp/tmpri_861ie/ce75deix5v2ltuxilvqvbxmlr5qvlqmr22yvpthfi2chjjhlxkcn/cos_triton_poi_fused_cos_0.fatbin', '-gencode', 'arch=compute_100,code=sm_100', '-gencode', 'arch=compute_100,code=compute_100', '-gencode', 'arch=compute_110,code=sm_110', '-gencode', 'arch=compute_120,code=sm_120']' returned non-zero exit status 255.

To execute this test, run the following from the base repo dir:
    python test/inductor/test_aot_inductor_package.py TestAOTInductorPackageCpp_cuda.test_compile_standalone_cos

    ...

    stderr:
ptxas fatal   : PTX with .target 'sm_100a' cannot be compiled for architecture 'sm_100'

```

  seem to break due to removed suffixes. This PR does not strip suffixes in `_aoti_cuda_target_arch` which otherwise breaks with e.g., `.target sm_103a` PTX emitted by Trition.

    Authored with codex.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/187888
Approved by: https://github.com/jansel