[ROCm][CI] Enable permission change step for gfx950 runners (#173503)
Required for https://github.com/pytorch/pytorch/pull/173209 and https://github.com/pytorch/pytorch/pull/173407

Fixes errors such as: https://github.com/pytorch/pytorch/actions/runs/21373636766/job/61527758776
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1872, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test/test-reports/inductor.test_custom_post_grad_passes_1.1_f4a9c88412bb59fc_.log'
Error: Process completed with exit code 1.
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/173503
Approved by: https://github.com/jeffdaily