reorder cpuinfo and clog deps in TorchConfig.cmake
cpuinfo has some symbols that need to be resolved with clog.

Static builds fail without this fix with the following errors:
api.c:(.text+0xc2): undefined reference to `clog_vlog_fatal'
init.c:(.text+0x19d1): undefined reference to `clog_vlog_error'
processors.c:(.text+0x551): undefined reference to `clog_vlog_error'
smallfile.c:(.text+0x172): undefined reference to `clog_vlog_error'