[dynamo] support torch.Tensor() calls
Previously, dynamo fails on torch.Tensor() calls. This PR fixes this by replacing "torch.Tensor" with "torch.FloatTensor", or "torch.DoubleTensor", etc. depending on what the default tensor type is.

**More context**:
torch.Tensor is the old/legacy way to create tensors, which is now replaced with `torch.tensor()`. However, its behavior is slightly different: for example, `torch.tensor([1, 2, 3])` will create a tensor of ints, while `torch.Tensor([1, 2, 3])` will choose the dtype based on `torch.get_default_dtype()`. Note that nowadays, torch.Tensor is also used for subclassing purposes, e.g. for FakeTensors or other tensor subclasses.

Before this PR, dynamo did not support torch.Tensor() calls, e.g. this fails:

```python
def fn(x):
    return torch.Tensor(x)
x = [1, 2, 3]
torch._dynamo.optimize("eager")(fn)(x)
```

It fails in `get_fake_value` with:
```
RuntimeError: failed running call_function <class 'torch.Tensor'>(*([1, 2, 3],), **{}):
Creating a new Tensor subclass Tensor but the raw Tensor object is already associated to a python object of type FakeTensor
```

Actually, it's a fake tensor issue, i.e. this fails:
```python
x = [1, 2, 3]
with torch._subclasses.fake_tensor.FakeTensorMode():
    y = torch.Tensor(x)
```

This PR will only fix torch.Tensor() in dynamo, not in fake tensor.

The failure occurs in [THPVariable_pynew](https://github.com/pytorch/pytorch/blob/364f526b9cdf9818a7647b5e637efdee825d61a1/torch/csrc/autograd/python_variable.cpp#L1788) (basically c++ impl of torch.Tensor.__new__) when it calls [THPVariable_NewWithVar](https://github.com/pytorch/pytorch/blob/364f526b9cdf9818a7647b5e637efdee825d61a1/torch/csrc/autograd/python_variable.cpp#L1941).

Meanwhile, `torch.FloatTensor` and `torch.DoubleTensor` etc. behave very similar to torch.Tensor, except they have fixed dtype/device instead of relying on the global defaults, and are also implemented such that they don't fail under FakeTensorMode. So we can just replace `torch.Tensor` with the appropriate `torch.DtypeTensor` in dynamo.

[ghstack-poisoned]