Skip `test_tma_stable_reconstruct` on Python 3.13+
In Python 3.12 and lower the `__eq__` of the `TensorDescriptor` skipped
the actual comparison of the tensor when it was the same instance.
In newer Python versions default comparison is performed which yields a
bool-tensor that is then context-converted to `bool` which fails with
> RuntimeError: Boolean value of Tensor with more than one value is ambiguous