Fix for failure in test_autocast.py
The latest update to autocast.py added new tests which picked up an old failure.
Traceback (most recent call last):
  File "test_autocast.py", line 126, in test_autocast_fast_dtype
    self.assertEqual(gpu_fast_dtype, torch.half)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1693, in assertEqual
    super().assertEqual(x, y, msg=msg)
AssertionError: torch.half != torch.float16

I isolated and reproduced this bug with the following code:

>>> torch.get_autocast_cpu_dtype()
torch.half
>>> torch.get_autocast_cpu_dtype()
torch.bfloat16
>>> torch.get_autocast_cpu_dtype() == torch.bfloat16
False
>>> torch.get_autocast_gpu_dtype() == torch.half
False

This bug occurs on Jetson and x86 and is not hardware specific.
In the 21.10 backend the get_autocast_gpu_dtype function is defined in cpp as follows:
at::ScalarType get_autocast_gpu_dtype() {
  return autocast_gpu_dtype;
}
Then it gets exposed to python as follows:
static PyObject * get_autocast_gpu_dtype(PyObject* _unused, PyObject *arg){
  HANDLE_TH_ERRORS
  at::ScalarType current_dtype = at::autocast::get_autocast_gpu_dtype();
  return THPDtype_New(current_dtype, scalarTypeName(current_dtype));
  END_HANDLE_TH_ERRORS
The  issue is that torch.get_autocast_xxx_dtype() is basically returning a brand new instantiation of torch.float16/torch.half through THPDtype_New that behaves identically but is not an identical torch dtype object so the basic python == operator complains. I think for proper user experience this should be fixed.
Fix here.
After fix:
>>> import torch
>>> torch.get_autocast_gpu_dtype() == torch.float16
True
>>> torch.get_autocast_cpu_dtype() == torch.bfloat16
True