float2::x and float2::y may not be the same as float on ROCm
This causes ambiguity and can be triggered sometimes (e.g., by #35217). Explicitly convert them to float.

    error: conditional expression is ambiguous; 'const
    hip_impl::Scalar_accessor<float, Native_vec_, 0>' can be converted to
    'float' and vice versa