Check availability of accelerator in test_schedule
The device check contains a fallback if no accelerator is available but
doesn't check if one is available and only checks if support is available.

This causes tests to fail with e.g.
> RuntimeError: Found no NVIDIA driver on your system.

Add the `check_avail=True` argument.