Silence errors due to Hardswish.
Introduced in gh-36545, but unclear if that PR was problematic, the
new error messages look similar to already silenced ones about Module:

```
torch/nn/quantized/modules/activation.py:84: error: Name 'torch.nn.Hardswish' is not defined  [name-defined]
torch/nn/qat/modules/activations.py:5: error: Name 'nn.Hardswish' is not defined  [name-defined]
torch/nn/qat/modules/activations.py:17: error: Module has no attribute "Hardswish"  [attr-defined]
torch/quantization/default_mappings.py:18: error: Module has no attribute "Hardswish"  [attr-defined]
torch/quantization/default_mappings.py:49: error: Module has no attribute "Hardswish"  [attr-defined]
torch/quantization/fake_quantize.py:126: error: Module has no attribute "per_tensor_symmetric"  [attr-defined]
torch/quantization/fake_quantize.py:132: error: Module has no attribute "per_channel_symmetric"  [attr-defined]
```