Disable "-Wignored-qualifiers" for vec256_bfloat16.h (#66279)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/66279

This error appears when compiling with "-Wextra" and cannot be resolved by fixing the code since the return type of the instrinic being passed to `map` is fixed.

Fixes:
```
caffe2/aten/src/ATen/cpu/vec/vec256/vec256_bfloat16.h:204:28: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
  Vectorized<BFloat16> map(const __m256 (*const vop)(__m256)) const {
                           ^~~~~~
caffe2/aten/src/ATen/cpu/vec/vec256/vec256_bfloat16.h:204:28: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
  Vectorized<BFloat16> map(const __m256 (*const vop)(__m256)) const {
                           ^~~~~~
```

Test Plan: Sandcastle

Reviewed By: ngimel

Differential Revision: D31480888

fbshipit-source-id: 919c0d48c8ce13ce1106a9df124a077945e36707