Export CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_* (#11233)
Summary:
This PR resolved the following compilation errors on devgpu:
/home/mingzhe0908/pytorch/build/lib/libcaffe2_gpud.so: undefined reference to `caffe2::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_Tan()'
/home/mingzhe0908/pytorch/build/lib/libcaffe2_gpud.so: undefined reference to `caffe2::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_MaxPool3D()'
....

The same error has been happening with caffe2 build with debug mode before build_caffe2 was removed.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/11233

Reviewed By: orionr

Differential Revision: D9645527

Pulled By: mingzhe09088

fbshipit-source-id: 68a45aa7fd815cac41b7fd64cfd9838b3226345a