Fix caffe2 c++20 / windows build problem (#113963)
Summary:

 - `stderr: D:\full-fbsource\xplat\caffe2\torch\csrc\jit\codegen\fuser\cpu\fused_kernel.cpp(155): error C2440: '=': cannot convert from 'const wchar_t [28]' to 'wchar_t *'`

Test Plan: - CI

Reviewed By: h-friederich

Differential Revision: D50902536