`__cuda_array_interface__`: Use "<V2" for bfloat16.
Rationale: While Numpy doesn't support bfloat16 and therefore
there's no official typestr for bfloat16 in `__array_interface__`
(https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.interface.html#__array_interface__),
JAX/ml_dtypes uses "<V2":

```
>>> from jax import numpy as jnp
>>> jnp.bfloat16.dtype.str
'<V2'
```

Using the same in PyTorch has the upside of making the typestrs returned
by __cuda_array_interface__ identify the torch dtype uniquely.

(1) JAX itself just refuses to do `__cuda_array_interface__` for bfloat16:

```
>>> from jax import numpy as jnp
>>> jnp.arange(10, dtype=jnp.bfloat16).__cuda_array_interface__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: __cuda_array_interface__ is not supported for bfloat16 buffers.
```

(2) The "official" description of `__cuda_array_interface__` doesn't mention
bfloat16, it just references `__array_interface__`:
https://numba.readthedocs.io/en/stable/cuda/cuda_array_interface.html

(3) Ongoing issue for numpy to support bfloat16:
https://github.com/numpy/numpy/issues/19808

(4) Tweet that triggered this: https://x.com/HeinrichKuttler/status/1866761979349844211

(5) "<V2" is kinda weird, as it's a "little-endian void" type. When
given to Numpy, it gets turned into endian-agnostic:

```
>>> import numpy as np
>>> import ml_dtypes
>>> np.dtype("bfloat16").str
'<V2'
>>> np.dtype("<V2").str
'|V2'
```