[amd] fix unused variable device_flags
Summary:
get build error due to D53986297 (https://github.com/pytorch/pytorch/pull/119996)

```
caffe2/c10/cuda/__fb_c10_hipify_gen__/out/c10/hip/HIPStream.cpp:40:23: error: unused variable 'device_flags' [-Werror,-Wunused-variable]
static c10::once_flag device_flags[C10_COMPILE_TIME_MAX_GPUS];
```

Reviewed By: jianyuh, xw285cornell

Differential Revision: D54027737