TestTritonDotReduction.test_matmul_fp16 correct tol (#169682)
Fixes #168196.  Replaces #169588.

_check_equal calls torch._dynamo.utils.same with kwarg tol=1e-4. For fp16 dtype, torch.allclose() defaults to atol=1e-3 rtol=1e-5, but same() uses the single tol value to assign both, resulting in

Accuracy failed: allclose not within tol=0.0001.

Replacing _check_equal's `self.assertTrue(same(expect, actual))` with `self.assertEqual(expect, actual, atol=1e-4, rtol=1e-4)` reveals

```
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 16384 (0.0%)
Greatest absolute difference: 0.00390625 at index (66, 102) (up to 0.0001 allowed)
Greatest relative difference: 0.0006270408630371094 at index (66, 102) (up to 0.0001 allowed)
```

The solution here is to use same() with a tol=1e-3 to match default tolerance values for allclose and assertEqual.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169682
Approved by: https://github.com/jeffdaily

Co-authored-by: Jeff Daily <jeff.daily@amd.com>