[Do Not Land] Test remove glsl code gen (#90658)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/90658

Combination of
- D41197273
- D41354313
- D41358861

Want to debug OSS failures

Test Plan:
```
-- Build files have been written to: /Users/salilsdesai/pytorch/build
cmake --build . --target install --config Release
[28/1231] Building CXX object caffe2/CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o
FAILED: caffe2/CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o
/Users/salilsdesai/opt/anaconda3/envs/torch/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -I/Users/salilsdesai/pytorch/build/aten/src -I/Users/salilsdesai/pytorch/aten/src -I/Users/salilsdesai/pytorch/build -I/Users/salilsdesai/pytorch -I/Users/salilsdesai/pytorch/cmake/../third_party/benchmark/include -I/Users/salilsdesai/pytorch/third_party/onnx -I/Users/salilsdesai/pytorch/build/third_party/onnx -I/Users/salilsdesai/pytorch/third_party/foxi -I/Users/salilsdesai/pytorch/build/third_party/foxi -I/Users/salilsdesai/pytorch/build/caffe2/aten/src -I/Users/salilsdesai/pytorch/build/vulkan -I/Users/salilsdesai/pytorch/aten/../third_party/VulkanMemoryAllocator -I/Users/salilsdesai/pytorch/aten/../third_party/catch/single_include -I/Users/salilsdesai/pytorch/aten/src/ATen/.. -I/Users/salilsdesai/pytorch/third_party/miniz-2.1.0 -I/Users/salilsdesai/pytorch/torch/csrc/api -I/Users/salilsdesai/pytorch/torch/csrc/api/include -I/Users/salilsdesai/pytorch/c10/.. -isystem /Users/salilsdesai/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /Users/salilsdesai/pytorch/cmake/../third_party/googletest/googletest/include -isystem /Users/salilsdesai/pytorch/third_party/protobuf/src -isystem /Users/salilsdesai/pytorch/third_party/gemmlowp -isystem /Users/salilsdesai/pytorch/third_party/neon2sse -isystem /Users/salilsdesai/pytorch/third_party/XNNPACK/include -isystem /Users/salilsdesai/pytorch/third_party/ittapi/include -isystem /Users/salilsdesai/pytorch/cmake/../third_party/eigen -isystem /Users/salilsdesai/pytorch/third_party/ideep/mkl-dnn/third_party/oneDNN/include -isystem /Users/salilsdesai/pytorch/third_party/ideep/include -isystem /Users/salilsdesai/pytorch/third_party/googletest/googletest/include -isystem /Users/salilsdesai/pytorch/third_party/googletest/googletest -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN -DUSE_VULKAN_API -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wvla-extension -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-constexpr-not-const -Wno-missing-braces -Wunused-lambda-capture -Wunused-local-typedef -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-constexpr-not-const -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -mmacosx-version-min=12.6 -fPIE -DTH_HAVE_THREAD -std=gnu++17 -MD -MT caffe2/CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o -MF caffe2/CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o.d -o caffe2/CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o -c /Users/salilsdesai/pytorch/aten/src/ATen/test/vulkan_api_test.cpp
In file included from /Users/salilsdesai/pytorch/aten/src/ATen/test/vulkan_api_test.cpp:6:
In file included from /Users/salilsdesai/pytorch/aten/src/ATen/native/vulkan/api/api.h:5:
In file included from /Users/salilsdesai/pytorch/aten/src/ATen/native/vulkan/api/Common.h:8:
/Users/salilsdesai/pytorch/aten/src/ATen/native/vulkan/api/vk_api.h:12:10: fatal error: 'vulkan/vulkan.h' file not found
#include <vulkan/vulkan.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
[45/1231] Building CXX object caffe2/CMakeFiles/op_registr...n/src/ATen/core/op_registration/op_registration_test.cpp.o
ninja: build stopped: subcommand failed.

```

Differential Revision: D41917066

fbshipit-source-id: f4364f22270dfa4b3be435594241009dbfdc3cc2