[aoti] better error message for mixed device tensors (#173982)
Fixes #172739

Though the aot_export/aot_load API is deprecated, we should error out gracefully instead of segfault.

Error message now:

```
W0130 17:59:03.071000 1959179 torch/_export/__init__.py:71] +============================+
W0130 17:59:03.071000 1959179 torch/_export/__init__.py:72] |     !!!   WARNING   !!!    |
W0130 17:59:03.071000 1959179 torch/_export/__init__.py:73] +============================+
W0130 17:59:03.071000 1959179 torch/_export/__init__.py:74] torch._export.aot_compile()/torch._export.aot_load() is being deprecated, please switch to directly calling torch._inductor.aoti_compile_and_package(torch.export.export())/torch._inductor.aoti_load_package() instead.
Error: Mixed-device constants are only supported when the secondary device is CPU. Constant 'linear_weight' was compiled for a non-CPU device.
Error loading on CPU: create_func_( &container_handle_, num_models, device_str.c_str(), cubin_dir.empty() ? nullptr : cubin_dir.c_str()) API call failed at /data/users/shangdiy/pytorch/torch/csrc/inductor/aoti_runner/model_container_runner.cpp, line 121
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/173982
Approved by: https://github.com/desertfire