Generalize the testcase for a given world size
Currently, the test case fails when more than 4-ranks are used with the
following error:
NotImplementedError: Cannot copy out of meta tensor; no data!

The patch keeps existing functionality of supporting four-ranks or
devices, in addition, make the test case more generic for a given world_size, e.g. 8-ranks.