[ROCm] Move rocblas.h include out of anonymous namespace (#178767)
Fix for build failure caused by including `rocblas/rocblas.h` inside an anonymous namespace.

Fixes following build errors:
```
error: no template named 'unique_lock' in namespace 'at::cuda::(anonymous namespace)::std'
error: no template named 'shared_mutex' in namespace 'at::cuda::(anonymous namespace)::std'
error: no template named 'get' in namespace 'at::cuda::(anonymous namespace)::std'
error: no type named 'string' in namespace 'at::cuda::(anonymous namespace)::std'
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/178767
Approved by: https://github.com/jeffdaily