fix compile error with : undefined reference to symbol '_ZN3MPI8Datatype4FreeEv
compile with error that: mpi_test.cc.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv

caused by the miss for MPI link info. 

add to caffe2/CMakefiles.txt to compile it.