[JIT] Fix torch.jit.script for functions with many decorators (#87804)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/87804

Python's function parsing from the `ast` module records the line number of the function definition, not the first decorator. So this diff fixes crashes like this:

```
IndexError: vector::_M_range_check: __n (which is 10) >= this->size() (which is 8)
```

Test Plan: New unit test

Differential Revision: D40726352

fbshipit-source-id: c12ba0007781ee3b7f4ec7efacabfe87d1125839