Update on "Add RemoteTraceback for exception with multiple arguments"
Fixes #25522 #30147 #34130 #44631 #48709 #51663

Taking reference of #40437 and [python](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/process.py#L114-L131)

Due to lots of issues related to re-raising error, add a RemoteTraceback as the `__cause__` of the Exception in the main process.

When Python load object from different process using [pickle](https://docs.python.org/3/library/pickle.html#pickling-class-instances), it creates a new object with arguments. As the customized `Exception` is required for multiple arguments, which are not provided, it will causes the error.

```py
import torch.utils.data

class MyException(Exception):
    def __init__(self, msg, arg1, arg2):
        super().__init__(msg)

class MyDataset(torch.utils.data.IterableDataset):
    def __iter__(self):
        raise MyException("MyError", 1, 2)

if __name__ == '__main__':
    dl = torch.utils.data.DataLoader(MyDataset(), num_workers=1)
    list(iter(dl))
```

```
torch._utils._RemoteTraceback: Traceback (most recent call last):
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/worker.py", line 152, in _worker_loop
    fetcher = _DatasetKind.create_fetcher(dataset_kind, dataset, auto_collation, collate_fn, drop_last)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 52, in create_fetcher
    return _utils.fetch._IterableDatasetFetcher(dataset, auto_collation, collate_fn, drop_last)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 21, in __init__
    self.dataset_iter = iter(dataset)
  File "/Users/erjia/workspace/test/test_exception.py", line 14, in __iter__
    raise MyException("MyError", 1, 2)
__mp_main__.MyException: MyError


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test/test_exception.py", line 19, in <module>
    list(iter(dl))
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 518, in __next__
    data = self._next_data()
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 1200, in _next_data
    return self._process_data(data)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 1226, in _process_data
    data.reraise()
  File "/Users/erjia/workspace/pytorch/torch/_utils.py", line 420, in reraise
    raise self.exc
Exception: Re-raise the exception in DataLoader worker process 0
```

[ghstack-poisoned]