[Dynamo] Fix numpy error in test_numpy_torch_operators
When you inplace matmul two one dimensional numpy arrays,
numpy=="1.24.3" gives
> TypeError: In-place matrix multiplication is not (yet) supported. Use 'a = a @ b' instead of 'a @= b'.
but numpy=="1.25.2" gives
> ValueError: inplace matrix multiplication requires the first operand to have at least one and the second at least two dimensions.

This diff makes it so that newer versions of numpy does not fail on this
test because we do not catch ValueError.

An alternative solution would be to update the test cases to be 2
dimensional, but that would have impact on other operators being tested.