[precompile] nicer error message when caches are disabled
I commonly use the following alias for generating tlparses

```
function tlp {
  setopt rm_star_silent
  rm -rf ~/tmp/trace_logs/*
  TORCH_TRACE=~/tmp/trace_logs TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 "$@"
  tlparse ~/tmp/trace_logs --slug "$USER/$(uuidgen)/custom" --overwrite-manifold
}
```

and was surprised to see the following failure

```
(/home/bobren/local/a/pytorch-env) [9:18] devgpu009:/home/bobren/local/a/pytorch [130]
❯ tlp python pc.py
/home/bobren/local/a/pytorch/torch/_dynamo/pgo.py:539: UserWarning: dynamo_pgo force disabled by torch.compiler.config.force_disable_caches
  warn_once(
Traceback (most recent call last):
  File "/home/bobren/local/a/pytorch/pc.py", line 24, in <module>
    compiled_fn.save_compiled_function(path)
  File "/home/bobren/local/a/pytorch/torch/_dynamo/aot_compile.py", line 128, in save_compiled_function
    f.write(type(self).serialize(self))
  File "/home/bobren/local/a/pytorch/torch/_dynamo/aot_compile.py", line 143, in serialize
    type(compiled_fn).serialize_compile_artifacts(compiled_fn),
  File "/home/bobren/local/a/pytorch/torch/_dynamo/aot_compile_types.py", line 50, in serialize_compile_artifacts
    result = pickle.dumps(fn.compiled_fn.serialize())
TypeError: 'NoneType' object is not callable
```

which goes away if i remove TORCH_INDUCTOR_FORCE_DISABLE_CACHE=1

This PR adds a nicer error message

```
❯ tlp python pc.py
/home/bobren/local/a/pytorch/torch/_dynamo/pgo.py:539: UserWarning: dynamo_pgo force disabled by torch.compiler.config.force_disable_caches
  warn_once(
Traceback (most recent call last):
  File "/home/bobren/local/a/pytorch/pc.py", line 24, in <module>
    compiled_fn.save_compiled_function(path)
  File "/home/bobren/local/a/pytorch/torch/_dynamo/aot_compile.py", line 128, in save_compiled_function
    raise RuntimeError(
RuntimeError: Cannot precompile with torch._inductor.config.force_disable_caches=True; caching is required.
```

[ghstack-poisoned]