[coreml-backend-tool] fix pytorch-backended issue on new coremltools (#155543)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/155543

the new coreml tool is export mlpakage instead mlmodel in default option.  when we use new 8.0 coreml tool to convert to backend, the error is

```
Exception: MLModel of type mlProgram cannot be loaded just from the model spec object. It also needs the path to the weights file. Please provide that as well, using the 'weights_dir' argument.
```

Test Plan:
tested with internal workflow

Rollback Plan:

Reviewed By: shoumikhin

Differential Revision: D76325462