[caffe2][SDT] Check whether `TORCH_DISABLE_SDT` macro is defined before referencing it (#107149)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/107149

Some jobs in the next diff in stack (D48229150) fail with the following message:

```
stderr: In file included from xplat/caffe2/c10/cuda/CUDACachingAllocator.cpp:9:
xplat/caffe2/c10/util/static_tracepoint.h:4:6: error: 'TORCH_DISABLE_SDT' is not defined, evaluates to 0 [-Werror,-Wundef]
    !TORCH_DISABLE_SDT
```

When porting USDT macros to PyTorch in D47159249, I must have not hit a codepath which treated warnings as errors during testing.

This diff fixes the issue by first checking whether the `TORCH_DISABLE_SDT` macro is defined before trying to access it in the `static_tracepoint.h` header.

Test Plan:
Similar to D47159249, tested the following macro on test scripts with `libbpf` USDTs:
* `CAFFE_DISABLE_SDT`

Reviewed By: chaekit

Differential Revision: D48251736

fbshipit-source-id: 7c0ef636274e015b109f5377ec8c1fe2c493a5a4