Update on "Implement faster gradcheck but not enabled for most things"
Plan for rollout:
 - This PR should only land the code (with some basic checks that run on both -- all we do here is for each of the test_gradcheck_* tests, we wrap it in a function which takes `fast_mode` as a param, and call it twice). Otherwise, every other call to gradcheck will be slow_mode.
   - This should help us verify that a) slow is still working as expected b) basic functionality of fast works
 - A separate PR is responsible for enabling the fast_mode=True flag, and selectively disabling for the cases the fail.
 - In the complex case, we don't run the fast version ATM. (in terms of performance, since roughly half the time taken is for complex dtype, by speeding up the non-complex case by 10-20x we should only see a ~2x speedup overall.
 - The logic for the above is mainly handled by the gradcheck wrapper

TODOs and open questions (not necessarily blocking this PR):
 - Better understand possible cases when fast succeeds but slow fails (this will be ongoing, as new tests are added)
 - ~How do we think about atol/rtol~ (scale atol, keep rtol as-is)
 - reenable fast-gradcheck for complex numbers
 - when inputs are uncoalesced we don't truly test this case because we coalesce the inputs before calling function. Revisit this when https://github.com/pytorch/pytorch/pull/52874/files is landed

Non-determinism issues:
- ops that do not have deterministic implementation (as documented https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms)
  - test_pad_cuda (replication_pad2d) (test_nn)
  - interpolate (test_nn)
  - cummin, cummax (scatter_add_cuda_kernel) (test_ops)
  - test_fn_gradgrad_prod_cpu_float64 (test_ops)
- cases where setting torch.manual_seed fixes
  - RRelu (new module tests)

Numerical precision issues:
- jacobian mismatch: test_gelu (test_nn, float32, not able to replicate locally),
- cholesky_solve (test_linalg): https://app.circleci.com/pipelines/github/pytorch/pytorch/296020/workflows/27142826-4629-44e9-a365-b412aec374c5/jobs/12113886
- cumprod (test_ops)

Not yet replicated:
 - test_relaxed_one_hot_categorical_2d (test_distributions)

### Developer Experience
Sample output when jacobian mismatch occurs:
```
Traceback (most recent call last):
  File "/home/s/local/pytorch4/test/test_autograd.py", line 4220, in test_gradcheck_jacobian_mismatch
    check(fast_mode=True)
  File "/home/s/local/pytorch4/test/test_autograd.py", line 4196, in check
    gradcheck(fn, (x,), fast_mode=fast_mode)
  File "/home/s/local/pytorch4/torch/testing/_internal/common_utils.py", line 2067, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/s/local/pytorch4/torch/autograd/gradcheck.py", line 1020, in gradcheck
    if not fast_gradcheck(fail_test, seeded_func, func_out, tupled_inputs, outputs, eps, rtol,
  File "/home/s/local/pytorch4/torch/autograd/gradcheck.py", line 915, in fast_gradcheck
    return fail_test(get_notallclose_msg(a, n, i, j, prefix) + jacobians_str)
  File "/home/s/local/pytorch4/torch/autograd/gradcheck.py", line 996, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(0.9195)
analytical:tensor(0.9389)

The above quantities relating the numerical and analytical jacobians are computed 
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background 
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000]])
Analytical:
tensor([[1.0100, 0.0100, 0.0100, 0.0100],
        [0.0100, 1.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 1.0100, 0.0100],
        [0.0100, 0.0100, 0.0100, 1.0100]])

The max per-element difference (slow mode) is: 0.010000000000054632.
```
Additionally, if the per-element difference is small i.e., `allclose(analytical_slow, numerical_slow, rtol, atol) is True` we follow up with this message:
```
Fast gradcheck failed but element-wise differences are small. This means that the
test might've passed in slow_mode!

If you are adding a new operator, please file an issue and then use one of the
workarounds. The workaround depends on how your test invokes gradcheck/gradgradcheck.

If the test
- manually invokes gradcheck/gradgradcheck, then call gradcheck/gradgradcheck
  with `fast_mode=False` as a keyword argument.
- is OpInfo-based (e.g., in test_ops.py), then modify the OpInfo for the test
  to have `gradcheck_fast_mode=False`
- is a Module test (e.g., in common_nn.py), then modify the corresponding
  module_test entry to have `gradcheck_fast_mode=False`
```

[ghstack-poisoned]