Fix timeout in `test_share_memory` on error
When the RPC init fails, e.g. due to
> RuntimeError: In operator() at tensorpipe/common/ibv.h:172 "": Invalid argument
(see https://github.com/pytorch/tensorpipe/issues/413) then the
`rpc.shutdown` will hang forever waiting for processes that didn't start.

So do that only after successful `rpc.init_rpc`.