Fix nightly build of C++ docs (#100845)
The fix is to upgrade breathe version (and sphinx accordingly), for example https://github.com/pytorch/pytorch/actions/runs/4898593997/jobs/8749163278.

```
Exception occurred:
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 104, in DomainDirectiveFactory
    'function': (python.PyModulelevel, 'function'),
AttributeError: module 'sphinx.domains.python' has no attribute 'PyModulelevel'
```

This was missed in https://github.com/pytorch/pytorch/pull/100601 because `RUN_DOXYGEN` is only set to true in the nightly job.  Specifically, the 2 plugins `breathe` and `exhale` are only used when `RUN_DOXYGEN` is set to true https://github.com/pytorch/pytorch/blob/main/docs/cpp/source/conf.py#L37-L42

### Testing

https://github.com/pytorch/pytorch/actions/runs/4910813882/jobs/8771541636 passes with RUN_DOXYGEN set to true and C++ docs looks ok https://docs-preview.pytorch.org/100845/cppdocs/index.html
Pull Request resolved: https://github.com/pytorch/pytorch/pull/100845
Approved by: https://github.com/kit1980, https://github.com/atalman, https://github.com/ZainRizvi, https://github.com/malfet