Avoid compilation errors like below: (#1773)
./c10/util/variant.h:2256:9: error: definition of implicit copy
constructor for 'impl<c10::SmallVector<long, 5>, at::Tensor>' is
deprecated because it has a user-declared copy assignment operator
[-Werror,-Wdeprecated-copy]
  impl& operator=(const impl& other) = default;
          ^
../c10/util/variant.h:2393:3: note: in implicit copy