Add Lazy backend type string (#84228) (#84228)
Summary:
As the title suggest, the `Lazy` case was missing the in the `backend_to_string` switch case causing
```
RuntimeError: Unimplemented backend Lazy
```
when called with a lazy backend.

GitHub CC:
wconstab Krovatkin desertfire

Pull Request resolved: https://github.com/pytorch/pytorch/pull/84228
Approved by: https://github.com/wconstab

Test Plan: contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/7371761d9cc4a1c235f65aff07452da7de482eae

Reviewed By: mehtanirav

Differential Revision: D39123435

fbshipit-source-id: 7ea89b1863040ac4347c427d34d608692eb52936