[Inductor] Skip illegal launch grid values as 'inf' during autotune (#181899)
Summary:

### Issue
When generating auto-tuning configs, we do max grid size check only using size_hitns.

However, when running the auto-tuning code, we generate kernel inputs that could be much larger than size hints.

We need autotune code runtime guard against the max grid size over flow as well.

For the internal use case, we have the below kernel failing when XBLOCK=2 (xnume=7,516,192,768)

```
triton_heuristics.reduction(
    size_hints={'x': 8192, 'r0_': 128},
    reduction_hint=ReductionHint.DEFAULT,
    filename=__file__,
    triton_meta={...},
    inductor_meta={...}
)
triton.jit
def triton_red_fused_<failing_kernel_name>_123(
...

buf1036 = generate_example_value((64, 4096, 4096, 7), (117440512, 28672, 7, 1), 'cuda:0', torch.bool, 0, (64, 4096, 4096, 7))
with torch.cuda._DeviceGuard(0):
    triton_red_fused_<failing_kernel_name>_123.run(buf1034, buf1035, buf1036, 7, 4096, 4096, 7516192768, 100, stream=stream0)
```



### Fix
- generate a runtime check for grid sizes, throw customized error when overflowing
- relying on existing invalid config capture + skip logic to not crash the autotune process, hence lifting up the substr into `INVALID_CONFIG_ERR_SUBSTR` to make it more maintainable
- also centrialize the usage of max grid sizes into a common constant

Test Plan:
Failure repro: https://www.internalfb.com/intern/testinfra/testrun/25614222898236081

```
OverflowError: signed integer is greater than maximum
```

- passed new unit test
- internal use case resolved
- OSS CI

Reviewed By: lurunming

Differential Revision: D103032505