Fix the onnx import error
Summary:
The ExportTypes was removed from torch.onnx, but it is still referenced in code. This leads to error
```
ImportError: cannot import name 'ExportTypes' from 'torch.onnx'
```

This change add back the correct the reference to ExportTypes

Test Plan: Test run downstream code that has dependency on pytext.utils.onnx and see the error is gone.

Differential Revision: D64340520