Back out "Revert D53492220: Back out "[pytorch][PR] [Inductor] GEMM shape padding improvements""
Summary:
Original commit changeset: 13b7808d2340

Original Phabricator Diff: D53492220

The original PR is causing issue in inductor: 

```
LoweringException: AssertionError: TensorBox(StorageBox(
  ComputedBuffer(name='buf168', layout=FlexibleLayout('cuda', torch.bfloat16, size=[4144, 3840], stride=[3840, 1]), data=Pointwise(
    'cuda',
    torch.bfloat16,
    def inner_fn(index):
        i0, i1 = index
        tmp0 = ops.load(buf148, 192 * ModularIndexing(i1, 1, 20) + 3840 * i0 + ModularIndexing(i1, 20, 192))
        return tmp0
    ,
    ranges=[4144, 3840],
    origin_node=None,
    origins={addmm_default_7}
  ))
))
  target: aten.addmm.default
  args[0]: TensorBox(
    View(
      ReinterpretView(
        StorageBox(
          ExternKernelOut(
            python_kernel_name='extern_kernels.bmm',
            name=buf148,
            layout=FixedLayout('cuda', torch.bfloat16, size=[4144, 20, 192], stride=[3840, 192, 1]),
            inputs=[ComputedBuffer(name='buf147', layout=FlexibleLayout('cuda', torch.bfloat16, size=[4144, 20, 40], stride=[800, 40, 1]), data=Pointwise(
              'cuda',
              torch.b...
```

Test Plan: CI

Differential Revision: D53524871