Update on "[sdpa] make sure to recompile if alignment is different than before"
An example from Qwen2-7B
- This come from running torch.compile with a sequence length that is
divisible by 8 (no padding needed). Run1.
- If we then run the compiled model with a difference length that isn't
divisible by 8 (requires padding). Run2.
- Then we'll see this error.
> RuntimeError: attn_bias.stride(2) = 6102, and should be a multiple of 4.
- We only see the error because we did not recompile on Run 2.

Size hint doesn't guard, so the fix is to use `guard_or*` to guard. 




cc voznesenskym penguinwu EikanWang jgong5 Guobing-Chen XiaobingSuper zhuhaozhe blzheng wenzhe-nrv jiayisunx ipiszy chenyang78 kadeng muchulee8 amjames chauhang aakhundov coconutruben

[ghstack-poisoned]