Update on "[DataPipe] Fix error message coming from single iterator constraint"
Fixes https://github.com/pytorch/data/issues/516

* Prevent confusion by not adding the extra string about `__iter__` when the exception is raised because of single iterator constraint
* Added a missing space
* Make sure `__len__` exists before calling it during exception handling


Exception example:
```python
from torchdata.datapipes.iter import IterableWrapper

source_dp = IterableWrapper(range(10))
it1 = iter(source_dp)
next(it1)
it2 = iter(source_dp)
next(it2)
next(it1)
```
Will raise:
```
Traceback (most recent call last):
  File "/Users/scratch/fast_forward.py", line 32, in <module>
    next(it1)
  File "/Users/pytorch/torch/utils/data/datapipes/_typing.py", line 524, in wrap_generator
    _check_iterator_valid(datapipe, iterator_id)
  File "/Users/pytorch/torch/utils/data/datapipes/_typing.py", line 445, in _check_iterator_valid
    raise RuntimeError(_gen_invalid_iterdatapipe_msg(datapipe) + _feedback_msg)
RuntimeError: This iterator has been invalidated because another iterator has been created from the same IterDataPipe: IterableWrapperIterDataPipe(deepcopy=True, iterable=range(0, 10))
This may be caused multiple references to the same IterDataPipe. We recommend using `.fork()` if that is necessary.
For feedback regarding this single iterator per IterDataPipe constraint, feel free to comment on this issue: https://github.com/pytorch/data/issues/45.
```

[ghstack-poisoned]