Increase clarity of CUDA errors by including excerpt from logs
CUDA 12.9 introduced the CUDA_LOG_FILE=... env var which prints very detailed and useful explanation of CUDA errors (e.g., the opaque and cryptic "invalid value" resolves to exactly what argument had a bad value and why).

A suggestion to users to enable this was included in https://github.com/pytorch/pytorch/pull/181011.

This same error log is also accessible programatically, thus a more robust approach is to systematically include the relevant lines from the log when we encounter a CUDA error and raise an exception.

The original attempt at this was using the cuLogsCurrent API which relies on CUDA's internal process-wide buffer of the last 100 error log messages. It enabled a very clean design, where we got a pointer to the end of the log before issuing a call, and thus allowed us after the call to retrieve only the newer messages, that were logged during that call, and avoid spurious ones.

This was however deemed too expensive, especially the unconditional preparation step that occurs for every CUDA call, including in the happy-path. The benchmark showed that this added 24-27 nanoseconds to each call, which for some very lightweight calls (such as cuCtxGetCurrent) could make them 6x slower. Moreover, this was subject to multithreaded contention, reaching latencies of 1.9-6.9 microseconds for 32 threads.

We thus opted for an alternative solution, which installs a global singleton callback with CUDA through which it gets notified of new error messages. This approach relies on the undocumented observation that the callback is invoked inline by the CUDA function call that experiences the error, from the same calling thread. This has multiple benefits, as it naturally allows us to filter only the messages that are relevant to the current thread and, via a thread-local structure, it permits a synchronization free design (no locks or atomic).

The happy-path boils down to just resetting a thread-local counter to 0. If a successfull CUDA call emits log messages, we'll also have to incur the call of copying them to our own thread-local buffer. All other costs are only paid when entering the error-path.

We have observed that the overhead in practice amounts to 1-2 nanoseconds, and stays constant even for multiple threads.

There is extra complexity in this approach coming from the fact that these are driver-level functions, thus we need a careful indirection to access them, which makes the code a bit cumbersome.

Here's an example of what this gives:

```
AcceleratorError: CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
The CUDA driver logged these messages, which may provide useful details:
Device-launched graphs and conditional nodes do not support MEM_ALLOC nodes
Returning 1 (CUDA_ERROR_INVALID_VALUE) from cuGraphInstantiateWithFlags
```

This also appears to report asynchronous kernel errors. If such an error occurs during a call to `cudaDeviceSynchronize` a log message such as this is emitted:
```
Returning 700 (CUDA_ERROR_ILLEGAL_ADDRESS) from cuCtxSynchronize_v2
```
whereas if a kernel had previously failed before the call this additional message appears as well:
```
Sticky error detected
```

ghstack-source-id: a575a6dd852b96fcca38be3a0f4d0a65a7656209
ghstack-comment-id: 5104215809
Pull-Request: https://github.com/pytorch/pytorch/pull/191334