Update on "Add torch.sparse.enable_sparse_outputs decorator of gradcheck that allows gradcheck input function to return sparse tensors"
As in the title.

This PR addresses the same problem as https://github.com/pytorch/pytorch/pull/97825 but using a different approach.

Currently, gradcheck input function is not allowed to return sparse tensors:
```python
>>> x = torch.tensor([[0, 1], [2, 3]], dtype=torch.float64).to_sparse().requires_grad_(True)
>>> torch.autograd.gradcheck(lambda x: x, x)
...
ValueError: Sparse output is not supported at gradcheck yet. Please call to_dense(masked_grad=...) on the output of fn for gradcheck.
```

This PR introduces a gradcheck decorator that adds sparse output support at gradcheck. For example:
```python
>>> gradcheck = torch.sparse.enable_sparse_outputs(torch.autograd.gradcheck)
>>> gradcheck(lambda x: x, x)
True
```

The advantage of having such a decorator is that users of gradcheck don't need to bother with calling `to_dense(masked_grad=...)` on the output of fn for gradcheck. The decorator will take care of using the correct `masked_grad` argument for the `to_dense` method call.

Discussion: should this feature be incorporated into torch.autograd.gradcheck?




cc ezyang albanD zou3519 gqchen nikitaved soulitzer Lezcano Varal7

[ghstack-poisoned]