[xpu] Support torch.xpu.mem_get_info on pluggable allocator (#197412)
# Motivation
Without this code change, `torch.xpu.mem_get_info` and `torch.accelerator.get_memory_info` doesn't support on pluggable allocator.
```bash
(guangyey) sdp@emr7470:~/guangyey/pytorch$ pytest test/test_xpu.py -k test_xpu_pluggable_allocator
==================================================== test session starts =====================================================
platform linux -- Python 3.10.14, pytest-9.1.1, pluggy-1.6.0
rootdir: /home/sdp/guangyey/pytorch
configfile: pytest.ini
plugins: hypothesis-6.156.6, anyio-4.14.2
collected 190 items / 189 deselected / 1 selected
Running 1 items in this shard

test/test_xpu.py [1/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=dummy_allocator -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/sdp/guangyey/pytorch/torch/include -isystem /home/sdp/guangyey/pytorch/torch/include/torch/csrc/api/include -isystem /opt/intel/oneapi/compiler/2026.0/include -isystem /opt/intel/oneapi/compiler/2026.0/include/sycl -isystem /home/sdp/miniforge3/envs/guangyey/include/python3.10 -fPIC -std=c++20 -c /home/sdp/.cache/torch_extensions/py310_cpu/dummy_allocator/main.cpp -o main.o
[2/3] icpx main.o -o sycl_dlink.o -fsycl -fsycl-link --offload-compress -fsycl-targets=spir64_gen,spir64 -Xs "-device bmg"
Compilation from IR - skipping loading of FCL
Build succeeded.
[3/3] c++ main.o sycl_dlink.o -shared -L/home/sdp/guangyey/pytorch/torch/lib -lc10 -lc10_xpu -ltorch_cpu -ltorch_xpu -ltorch -ltorch_python -L/opt/intel/oneapi/compiler/2026.0/lib -lsycl -o dummy_allocator.so
/usr/bin/x86_64-linux-gnu-ld.bfd: sycl_dlink.o: warning: relocation in read-only section `.rodata'
/usr/bin/x86_64-linux-gnu-ld.bfd: warning: creating DT_TEXTREL in a shared object
Traceback (most recent call last):
  File "<string>", line 48, in <module>
  File "/home/sdp/guangyey/pytorch/torch/xpu/memory.py", line 212, in mem_get_info
    return torch._C._xpu_getMemoryInfo(device)
NotImplementedError: getMemoryInfo is not implemented for this allocator yet.
```
With this fix, they support.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/197412
Approved by: https://github.com/gujinghui
ghstack dependencies: #195987