fix: compilation issues in mem_eff_attention with clang (#183102)
This change fixes a few issues when compiling `mem_eff_attention` with `clang`:

Missing `tuple` header:
```console
In file included from third_party/py/torch/aten/src/ATen/native/transformers/cuda/mem_eff_attention/kernel_forward.h:10:
In file included from third_party/py/torch/aten/src/ATen/cuda/PhiloxUtils.cuh:4:
third_party/py/torch/aten/src/ATen/cuda/detail/UnpackRaw.cuh:17:1: error: implicit instantiation of undefined template 'std::tuple<unsigned long, unsigned long>'
   17 | unpack(at::PhiloxCudaState arg) {
      | ^
third_party/crosstool/v18/stable/src/libcxx/include/__fwd/tuple.h:30:7: note: template is declared here
   30 | class tuple;
      |       ^
```

Missing `typename`:
```console
third_party/py/torch/aten/src/ATen/native/transformers/cuda/mem_eff_attention/kernel_forward.h:719:45: error: missing 'typename' prior to dependent type name 'MM1::LayoutB' (aka 'cutlass::layout::RowMajor')
  719 |             typename MM1::IteratorB::Params{MM1::LayoutB(p.v_strideM)},
      |                                             ^~~~~~~~~~~~
third_party/py/torch/aten/src/ATen/native/transformers/cuda/mem_eff_attention/kernel_forward.h:1013:45: error: missing 'typename' prior to dependent type name 'MM1::LayoutB' (aka 'cutlass::layout::RowMajor')
 1013 |             typename MM1::IteratorB::Params{MM1::LayoutB(p.v_strideM)},
      |                                             ^~~~~~~~~~~~
```

`clang` is not able to disambiguate and resolve correctly:
```console
third_party/py/torch/aten/src/ATen/native/transformers/cuda/mem_eff_attention/kernel_backward.h:2404:5: error: reference to overloaded function could not be resolved; did you mean to call it?
 2404 |     MatmulQK::Mma::prologue(
      |     ^~~~~~~~~~~~~~~~~~~~~~~
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/183102
Approved by: https://github.com/Skylion007