Update on "inductor: fix convert_shape_to_symint"
When `lst` is composed of a mix of static shapes and `sympy.Expr`, convert static shapes to ints and `sympy.Expr` to `symints`.
The old logic requires that all of the elements of `lst` be static and it can then convert them to ints.

Fix `yolov3` error on CPU: `AttributeError: 'int' object has no attribute 'free_symbols'`

cc mlazos soumith voznesenskym yanboliang penguinwu anijain2305 EikanWang jgong5 Guobing-Chen XiaobingSuper zhuhaozhe blzheng Xia-Weiwen wenzhe-nrv jiayisunx peterbell10 desertfire

[ghstack-poisoned]