Fix PyTorch build error on ppc64le
The PyTorch build breaks when building from tip on ppc64le with following error
pytorch/aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp:863:46: error: no matching function for call to 'at::vec::DEFAULT::Vectorizedc10::qint8::dequantize(at::vec::DEFAULT::Vectorized&, at::vec::DEFAULT::Vectorized&)

Issue reported #115165

This patch fixes the build issue.