fix build for symm mem by setting cmake dependencies (#172912)
Without this sometimes (perhaps due to different build order) build fails with
```
  /home/dev/meta/2_pytorch/torch/csrc/distributed/c10d/cuda/utils.cpp:1:10:
      fatal error: cuda_runtime.h: No such file or directory
          1 | #include <cuda_runtime.h>
            |          ^~~~~~~~~~~~~~~~
      compilation terminated.
      [2/816] Building CXX object
```
authored by claude.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/172912
Approved by: https://github.com/drisspg, https://github.com/malfet