Update on "[CI]Fix iOS CI"
### Summary

Seems like starting from macOS 10.15, we can no longer get access to the `Downloads` folder in our macOS machines. 

```
permissionError: [Errno 1] Operation not permitted: '/Users/distiller/Downloads'
```

The fix is to change the conda download directory to ${HOME}

### Test Plan

- iOS jobs are back to normal
- Don't break other jobs

Differential Revision: [D18717380](https://our.internmc.facebook.com/intern/diff/D18717380)