[dynamo] Slightly better error message if key not in dict (#117902)
Was debugging an export issue, and currently when `key` does not exist in `self.items`, the error message is
```
  File "/opt/pytorch/torch/_dynamo/variables/dicts.py", line 208, in getitem_const
    return self.items[key]
           ~~~~~~~~~~^^^^^
torch._dynamo.exc.InternalTorchDynamoError: <torch._dynamo.variables.dicts.ConstDictVariable._HashableTracker object at 0x7fd7697cbf90>
```
This PR changes it to be the following.
```
File "/data/users/angelayi/pytorch/torch/_dynamo/variables/dicts.py", line 199, in getitem_const
    raise KeyError(arg.value)
torch._dynamo.exc.InternalTorchDynamoError: shape
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/117902
Approved by: https://github.com/williamwen42