Update on "fix mypi in utils/_sympy/functions.py"
Signed-off-by: Bob Ren <bobrenfb.com>

Turns out older versions of python, in particular 3.8 shows errors that 3.12 doesn't. I managed to fix all the type errors except one.

```
(py38) [15:48] devvm1521:/home/bobren/local/pytorch dmypy check torch/utils/_sympy/functions.py
torch/utils/_sympy/functions.py:1159:5: error: Signature of "__repr__" incompatible with supertype "Printable"  [override]
torch/utils/_sympy/functions.py:1159:5: note:      Superclass:
torch/utils/_sympy/functions.py:1159:5: note:          def __str__(Printable, /) -> Any
torch/utils/_sympy/functions.py:1159:5: note:      Subclass:
torch/utils/_sympy/functions.py:1159:5: note:          def __repr__(self) -> Any
```

I don't really understand the error. I looked in both our codebase and sympy's codebase for `def __str__(Printable` and couldn't find it.

cc jgong5 mingfeima XiaobingSuper sanchitintel ashokei jingxu10

[ghstack-poisoned]