Fix error message stack overflow
When the given input size is larger than expected, weight_sizes is k-length but only has weight_dim numbers. And it causes the confusing error message:
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 256 5 3 3 3987964488216321853 94670871813000, but got 6-dimensional input of size [1, 61, 1, 5, 64, 64] instead