Fix issues with Werror=range-loop-construct
Was seeing compilation issues introduced in ce8716f59 in our internal
builds. Build errors look like:

```
fbcode/caffe2/aten/src/ATen/core/dispatch/DispatchKeyExtractor.h:145:23: error: loop variable 'tensor' creates a copy from type 'const at::Tensor' [-Werror=range-loop-construct]
  145 |         for (const at::Tensor tensor : ivalue.toTensorList()) {
      |
```

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>