[AOTI] Use arg signature to derive the right kernel input type for "sympy.Integer" as well (#169135)
## Issue

Previously when we have `arg_type` of sympy.Integer, we'll use `int` as its type in generated cpp wrapper code all the time. It'll cause IMA if the arg is actually of type i64.

Can see this [gist](https://gist.github.com/sevenEng/0cb7aaa2860fbc5a94ccf5b63ac83a59) for the generated cpp code from the model in added unit test, noticing "**int var_2 = load_seed_offset;**" from "**triton_poi_fused_rand_0**", where it should be **int64_t** instead.

## Fix

When matching and generating the arg declaration line in cpp wrapper code, give the "arg signature" branch more precedence over the default "int" and "float", so that we could find the right type.

## Unit test

before the patch, we'll see IMA from the unit test:

```
$ pytest -k test_constant_int_kernel_input test/inductor/test_aot_inductor.py
================================================================================================================================================================================= test session starts =================================================================================================================================================================================
platform linux -- Python 3.12.9, pytest-7.3.2, pluggy-1.5.0
rootdir: /data/users/q1l1/pytorch
configfile: pytest.ini
plugins: xdoctest-1.1.0, hypothesis-5.35.1, xdist-3.3.1, subtests-0.13.1, rerunfailures-14.0, flakefinder-1.1.0, cpp-2.3.0
collected 922 items / 919 deselected / 3 selected
Running 3 items in this shard
test/inductor/test_aot_inductor.py sError: CUDA driver error: an illegal memory access was encountered
Fs                                                                                                                                                                                                                                                                                                                                          [100%]
====================================================================================================================================================================================== FAILURES =======================================================================================================================================================================================
_________________________________________________________________________________________________________________________________________________________ AOTInductorTestABICompatibleGpu.test_constant_int_kernel_input_cuda _________________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/data/users/q1l1/pytorch/test/inductor/test_torchinductor.py", line 14720, in new_test
    return value(self)
           ^^^^^^^^^^^
  File "/data/users/q1l1/pytorch/test/inductor/test_aot_inductor.py", line 7651, in test_constant_int_kernel_input
    AOTIRunnerUtil.run(Model(), example_inputs)
  File "/data/users/q1l1/pytorch/test/inductor/test_aot_inductor_utils.py", line 191, in run
    return optimized(*example_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q1l1/.conda/envs/pytorch-3.12/lib/python3.12/site-packages/torch/export/pt2_archive/_package.py", line 732, in __call__
    flat_outputs = self.loader.boxed_run(flat_inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: run_func_( container_handle_, input_handles.data(), input_handles.size(), output_handles.data(), output_handles.size(), reinterpret_cast<AOTInductorStreamHandle>(stream_handle), proxy_executor_handle_) API call failed at /data/users/q1l1/pytorch/torch/csrc/inductor/aoti_runner/model_container_runner.cpp, line 145
To execute this test, run the following from the base repo dir:
    python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleGpu.test_constant_int_kernel_input_cuda
This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
unimplemented []
stats [('calls_captured', 11), ('unique_graphs', 1)]
inductor [('benchmarking.InductorBenchmarker.benchmark', 6), ('benchmarking.InductorBenchmarker.benchmark_gpu', 6), ('extern_calls', 5), ('pattern_matcher_count', 3), ('pattern_matcher_nodes', 3), ('async_compile_cache_miss', 3)]
graph_break []
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/home/q1l1/.conda/envs/pytorch-3.12/lib/python3.12/site-packages/torch/_dynamo/variables/user_defined.py:1815: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return ctor(*args, **kwargs)
/home/q1l1/.conda/envs/pytorch-3.12/lib/python3.12/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
=============================================================================================================================================================================== short test summary info ===============================================================================================================================================================================
FAILED [5.8375s] test/inductor/test_aot_inductor.py::AOTInductorTestABICompatibleGpu::test_constant_int_kernel_input_cuda - RuntimeError: run_func_( container_handle_, input_handles.data(), input_handles.size(), output_handles.data(), output_handles.size(), reinterpret_cast<AOTInductorStreamHandle>(stream_handle), proxy_executor_handle_) API call failed at /data/users/q1l1/pytorch/torch/csrc/inductor/aoti_runner/model_container_runner.cpp, line 145
==================================================================================================================================================================== 1 failed, 2 skipped, 919 deselected in 10.31s ====================================================================================================================================================================
Failed to destroy CUDA event in AOTInductor model: an illegal memory access was encountered
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169135
Approved by: https://github.com/jansel, https://github.com/desertfire