Fix compilation on Windows 10 (CUDA 10.0, Visual Studio 2017) (#19615)
Summary:
I want to use libtorch in a C++/CUDA project but as soon as I  include `<torch/torch.h>`, ".cu" files fail to compile:

`torch/csrc/jit/script/tree.h(64): error C3520: 'args': parameter pack must be expanded in this context`

This PR makes it build on my machine (don't know if it breaks anything though).
Pull Request resolved: https://github.com/pytorch/pytorch/pull/19615

Differential Revision: D15063712

Pulled By: ezyang

fbshipit-source-id: 7561e705f8f5b42b8e6a23430710b36508fee1ee