Fix failing dlpack tests (#169327)
Fix failing dlpack tests, which are currently failing on main.

On main, we get errors like:
```
File "/home/hugh/git/pytorch/torch/testing/_internal/common_utils.py", line 4298, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Object comparison failed: tensor([5, 1, 6, 5, 6], dtype=torch.uint8) != array([5, 1, 6, 5, 6], dtype=uint8)
```

Which if we dig a little give:
```
TestCase.assertEquals
try pair type <class 'torch.testing._comparison.NonePair'>
try pair type <class 'torch.testing._internal.common_utils.RelaxedBooleanPair'>
try pair type <class 'torch.testing._internal.common_utils.RelaxedNumberPair'>
try pair type <class 'torch.testing._internal.common_utils.TensorOrArrayPair'>
TensorOrArrayPair check inputs is instance
TensorOrArrayPair after check inputs is instance
_to_tensor tensor_like tensor([5, 1, 6, 5, 6], dtype=torch.uint8)
is torch tensor, returning tensor([5, 1, 6, 5, 6], dtype=torch.uint8)
_to_tensor tensor_like [5 1 6 5 6]
calling torch.as_tensor on  [5 1 6 5 6]
got exception Cannot export readonly array since signalling readonly is unsupported by DLPack.
```

This PR avoids this by doing the comparison without using TestCase.assertEquals.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/169327
Approved by: https://github.com/albanD