Update base for Update on "always save expr in sympy_expr_tracker"
In certain cases, such as with tensor subclasses like dtensor, symnodes are created in create_aot_state and stored within the dtensor spec. However, since create_aot_state runs without proxy tensor tracing enabled, no thunked proxy is created at this stage. As a result, when execution reaches aot_stage1_graph_capture, errors occur in our new internal training library, for example:

```
RuntimeError: 202048*s81 (140026802016016) is not tracked with proxy for <torch.fx.experimental.proxy_tensor.PythonKeyTracer object at 0x7f5a505fce20>
Adding TORCHDYNAMO_VERBOSE=1 doesn't seem to give me more information.
```

This PR modifies the code so that we can now use sympy_expr_tracker to map symnodes created outside of proxy-traced contexts to their corresponding thunked proxies when operating in traced contexts.

I'm still not certain if this is the right long term fix, but this at least unblocks the internal high priority workstream that is blocked on this issue.

cc ezyang EikanWang jgong5 wenzhe-nrv

[ghstack-poisoned]