[RPC Framework] Enable RemoteModule to directly send GPU tensors over the wire on TensorPipe RPC backend if a device map is provided
If the device map provided by RemoteModue is not empty, then TensorPipe RPC backend can support directly sending GPU tensors over the wire.

#Original PR issue: https://github.com/pytorch/pytorch/issues/51670


It seems that TensorPipe backend is much slower, and it causes test timeout if run `buck test @mode/dev-nosan caffe2/test/distributed/rpc:process_group_agent -- RemoteModule`, although the individual test can pass.

    ✗ Fail: caffe2/test/distributed/rpc:process_group_agent - test_unsupported_methods (fb.test_process_group_agent.ProcessGroupRemoteModuleTestWithFork) (124.102)
Test output:
> Repro command : $(cat "/tmp/tpx-20210428-165139.216124/6fc0ceaa-966b-49dd-a39f-afbea0e3b632/execution_command")
RuntimeError: Process 1 terminated or timed out after 100.16515851020813 seconds
  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/common_distributed.py", line 374, in wrapper
    self._join_processes(fn)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/common_distributed.py", line 614, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
stdout:
Could not download https://raw.githubusercontent.com/pytorch/test-infra/master/stats/slow-tests.json because of error <urlopen error [Errno 101] Network is unreachable>.
Couldn't download test skip set, leaving all tests enabled...
Timing out after 100 seconds and killing subprocesses.


Failed tests:

    ✗ caffe2/test/distributed/rpc:process_group_agent - test_forward_sync (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_bad_module (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_forward_async (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_remote_parameters (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_get_module_rref (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_forward_async_script (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_remote_parameters (fb.test_process_group_agent.ProcessGroupRemoteModuleTestWithFork)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_forward_async (fb.test_process_group_agent.ProcessGroupRemoteModuleTestWithFork)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_unsupported_methods (fb.test_process_group_agent.ProcessGroupRemoteModuleTestWithFork)
    ✗ caffe2/test/distributed/rpc:process_group_agent - test_forward_with_kwargs (test_process_group_agent.ProcessGroupRemoteModuleTestWithSpawn)

Differential Revision: [D28021672](https://our.internmc.facebook.com/intern/diff/D28021672/)

[ghstack-poisoned]