[c10] Make __assert_fail CUDA definition compilable with clang host compiler
Summary:
if nvcc is invoked with clang host compiler, it will fail with the following error due to the decorators mismatch defined in cuda and c10:
```
 error: attribute "noreturn" did not appear on original declaration
```

Test Plan: Build pytorch with clang

Differential Revision: D20204951

fbshipit-source-id: 36b1731a167c7c2097ee13cc70c683cb2ff2034a