Fix str format mismatch for WRONG_COMPILER_WARNING in cpp_extension
This is the error I got when trying to use sccache to wrap the compiler:

```
--- Logging error ---
Traceback (most recent call last):
  File "/my_conda_env/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/my_conda_env/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/my_conda_env/lib/python3.10/site-packages/torch/_logging/_internal.py", line 888, in format
    record.message = record.getMessage()
  File "/my_conda_env/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "/my_repo/setup.py", line 824, in <module>
    setuptools.setup(
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
    self.run_command(cmd)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/dist.py", line 1104, in run_command
    super().run_command(command)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 370, in run
    self.run_command("build")
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
    self.distribution.run_command(command)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/dist.py", line 1104, in run_command
    super().run_command(command)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
    self.distribution.run_command(command)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/dist.py", line 1104, in run_command
    super().run_command(command)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
    _build_ext.run(self)
  File "/my_conda_env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 368, in run
    self.build_extensions()
  File "/my_repo/setup.py", line 722, in build_extensions
    super().build_extensions()
  File "/my_conda_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 668, in build_extensions
    compiler_name, compiler_version = self._check_abi()
  File "/my_conda_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1167, in _check_abi
    _, version = get_compiler_abi_compatibility_and_version(compiler)
  File "/my_conda_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 467, in get_compiler_abi_compatibility_and_version
    logger.warning(WRONG_COMPILER_WARNING, compiler, _accepted_compilers_for_platform()[0], sys.platform, _accepted_compilers_for_platform()[0])
Message: '                               !! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Your compiler (%s) is not compatible with the compiler Pytorch wasbuilt with for this platform, which is %s on %s. Pleaseuse %s to compile your extension. Alternatively, you maycompile PyTorch from source using %s, and then you can also use%s to compile your extension.See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for helpwith compiling PyTorch from source.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                              !! WARNING !!'
Arguments: ('sccache', 'g++', 'linux', 'g++')
```