Update base for Update on "End-to-end ABI versioning PoC (version 1)"
This is part 1 of an end-to-end simulation of using the ABI versioning system that
- Uses `TORCH_TARGET_VERSION`
- Uses schema upgraders for `aoti_torch_call_dispatcher` ops when signatures of native ops change or a BC break is made
   - Updates ops.h as how we would expect it to change when the underlying op changes
- Changes the memory layout of a class in torch/headeronly and updates StableIValue conversions to handle this without the users knowledge

### Version 1 **(THIS PR)**
- Hardcodes TORCH_ABI_VERSION to 2.8.0 (simulating a fake state of the world in 2.8.0)
- Introduces a struct in torch/headeronly `Dummy` that has one member `int32_t id` (and threads it through to be a legitimate type that can be used in our native function schemas)
- Introduces a native_op `_test_versioning(Tensor self, Dummy dummy) -> Tensor` (that fills Tensor with Dummy.id)
- Adds a wrapper for `_test_versioning` in `torch/csrc/stable/ops.h` that calls it via `aoti_torch_call_dispatcher_v2`

### Version 2 https://github.com/pytorch/pytorch/pull/165284
- Hardcodes TORCH_ABI_VERSION to 2.9.0 (simulating a fake state of the world in 2.9.0)
- Changes the memory layout of `Dummy` (prepending an `int8_t` foo)
       - Keeping the old version in a separate namespace
       - Updates StableIValue conversions such that based on `extension_abi_version` or `aoti_torch_abi_version`, `from` and `to` will appropriately translate the old struct into the new struct or vice versa
- Adds a kwarg `scale` to ` _test_versioning(Tensor self, Dummy dummy, *, int scale=1) -> Tensor` (fills Tensor with Dummy.id * scale). (no default behavior change)
       - Registers an adapter for the schema for `aoti_torch_call_dispatcher`

### Version 3 https://github.com/pytorch/pytorch/pull/165285

- Simulates a fake state of the world in 2.10.0 (TORCH_ABI_VERSION is 2.10.0)
- Makes a BC-breaking change `_test_versioning(Tensor self, Dummy dummy, *, int scale=2) -> Tensor` (scale default 1 -> 2)
      - Gates the default value passed in to the ops.h header based on TORCH_FEATURE_VERSION


## Testing
We use a cpp_extension in this PR to add an op that 
- Creates a `Dummy(42)`
- Calls the high-level wrapper for `_test_versioning` from `torch/csrc/stable/ops.h`

And add a test that verifies the tensor passed in to our cpp extension op is filled with 42

We build this with
- No target version (i.e. TORCH_ABI_VERSION as the target version)
And run with torch builds from versions 1, 2 and 3. This verifies stableivalue conversions for Dummy are working in conjunction with the testing in version 2 above.
In all cases, the tests in this PR pass (i.e. tensor is just filled with Dummy.id as we expect), which means the adapters in the above PRs are working correctly.
- Target version < 2.8.0
(`error: ‘op’ is not a member of ‘torch::stable’` as expected), this verifies our macros gating based on `TORCH_TARGET_VERSION` are working correctly.




[ghstack-poisoned]