Update on "Docker: Fix valgrind install"
The docker builds are currently failing with a certificate error:
```
ERROR: cannot verify sourceware.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
```
https://github.com/pytorch/pytorch/pull/62445/checks?check_run_id=3827819732

This is because the cuda docker image's OpenSSL version is too old.
I've also removed the valgrind.org download attempt since the link
404s.

[ghstack-poisoned]