fix dtype issue in exclusive_scan_decoupled_lookback_64 (#171153)
Summary:
Fixing an issue

RuntimeError: Failed to run autotuning code block: An exception occurred in a subprocess:
...
AssertionError('initial value for `test_target` is of type int64, but the then block redefines it as int32')

Technical context:
At runtime:
test_target = -1 is only used to make the loop condition while test_target >= 0 false
It doesn't matter if it's int32 or int64 because -1 >= 0 is false regardless of dtype
The loop exits and the value is never used again
At compile time:
Triton's compiler analyzes all branches and checks type consistency
It sees test_target is initialized as index - 1 (int64)
Then in if flag == 2, it's reassigned to -1 (int32)
The compiler raises: 'initial value for test_target is of type int64[], but the then block redefines it as int32[]'

Test Plan:
* local lowering has succeeded
* re-publish with the built custom lowering pkg - ien.lower:de4373b
* unittest - `buck test @fbcode//mode/opt fbcode//caffe2/test/inductor:test_triton_helpers`

Differential Revision: D89705211

Pull Request resolved: https://github.com/pytorch/pytorch/pull/171153
Approved by: https://github.com/eellison