Cap num_stages to 1 on AMD in inductor's triton_heuristics.py (#160218)
Summary:

Running OmniFM v3 on AMD reveals that some inductor-generated triton kernels run into OutOfResource error even when num_stages=2. The fix is to change num_stages to 1.

Test Plan:
Running OmniFM v3 on AMD:
    $ hg graft D78741916
    $ hg graft D79739844
    $ scripts/ckluk/run_omnifm_v3_lwb_amd.sh  128 1152 -1

Without this diff:
     * https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-omnifm_v3_lwb-mi300x-ckluk-128gpu-1152bs--1batches-7287e5926a
         The error is:
RuntimeError: No valid triton configs. OutOfResources: out of resource: shared memory, Required: 73728, Hardware limit: 65536. Reducing block sizes or `num_stages` may help.,

With this diff:
* https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-omnifm_v3_lwb-mi300x-ckluk-128gpu-1152bs--1batches-59eec42bc2

The above runtime error disappears.

To show that this diff has no impact on NV:
      $ scripts/ckluk/run_omnifm_v3_lwb_nv.sh  128 1152 -1
Result:
https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-omnifm_v3_lwb-h100-ckluk-32gpu-512bs--1batches-4c3afb8a44

Rollback Plan:

Differential Revision: D79909743