bugfix: unwinder logic conflates load_bias and start addr (#181898)
The unwinder was using [load_bias, last_addr) as the
address range for libraries. This is only true when
p_vaddr is zero which is not always the case.

This commit removes that assumption by computing the
first address by combining load_bias and p_vaddr.

This failure was discovered in NVIDIA internal ARM CI
where the incorrect address range was messing up the
later binary search for addresses leading to missing
stack traces. This was caught by the following test:

```
______________ TestCudaAllocator.test_cpp_memory_snapshot_pickle _______________
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 3514, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_cuda.py", line 5382, in test_cpp_memory_snapshot_pickle
    self.assertTrue("::rand" in frame_text)
  File "/usr/lib/python3.12/unittest/case.py", line 727, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
To execute this test, run the following from the base repo dir:
    python test/test_cuda.py TestCudaAllocator.test_cpp_memory_snapshot_pickle
```

Testing:
- Test passes in NVIDIA's internal build
- Test passes in NVIDIA's internal build with customizations disabled
- Test passes in the PyTorch CI
Pull Request resolved: https://github.com/pytorch/pytorch/pull/181898
Approved by: https://github.com/drisspg, https://github.com/nWEIdia