Type promotion for most unary out_ ops for CPU
Summary:
This is a sample implementation of type promotion across a set of functions.

I think MKL will support converting floats to doubles in parallel, so this can be
a bit more optimized but leaving a TODO for now and will return after the same change
in CUDA.

Test Plan:
>>> a = torch.ones(3, dtype=torch.int32)
>>> c = torch.ones(3, dtype=torch.float64).mul(1.5)
>>> torch.sin(a, out=c)
tensor([0.8415, 0.8415, 0.8415], dtype=torch.float64)

>>> torch.sin(c, out=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Cannot store result of type torch.DoubleTensor to an output of type torch.IntTensor

>>> c = torch.ones([], dtype=torch.int32).mul(1.5)
>>> torch.sin(a, out=c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "sin" not implemented for 'torch.IntTensor'

Reviewers:

Subscribers:

Tasks:

Tags: