[release/2.6] Use miniforge instead of miniconda; pin to CMake 3.x; install sqlite (#2033)
* Using miniforge avoids rate limit errors when using miniconda
installer and default conda package channel: `[2025-04-15T19:29:19.374Z]
CondaHTTPError: HTTP 429 TERMS OF SERVICE RATE LIMIT EXCEEDED for url
<https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>`
* However, conda-forge channel brings in CMake 4.0 by default, which is
not compatible with older PyTorch release branches. Hence, pin CMake to
3.x
* Also, miniforge installation of conda does *not* install sqlite conda
package by default, hence explicitly install sqlite packages (needed in
[install_rocm.sh](https://github.com/ROCm/pytorch/blob/use_miniforge_release_2.6/.ci/docker/common/install_rocm.sh#L60))

Validation:
http://rocm-ci.amd.com/job/mainline-framework-pytorch-2.6-ub22-py3.10-ci/50/

---------

Co-authored-by: Pruthvi Madugundu <pruthvigithub@gmail.com>
(cherry picked from commit 9d0a4a1a72deeb4912dff1955bc222446507a3f9)
(cherry picked from commit ef2972838aa1b74578d2bfacd97bc875c18d2caf)

Fix conda issue for CentOS Stream 9 builds

(cherry picked from commit a8d551a1bd21fb79483fba236bf0840337ea5a92)