[quant][core][bug fix] Corrected at::to(memory_format=...) support for quantized tensors (#75540)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/75540

Previously, at::to(memory_format=....) was not properly supported for quantized tensors. e.g.,
```
In [1]: import torch
In [2]: x = torch.rand(2, 2, 2, 2)
In [3]: qx = torch.quantize_per_tensor(x, zero_point=2, dtype=torch.qint8, scale=0.5)
In [4]: qx = qx.to(memory_format=torch.channels_last)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [4], in <module>
----> 1 qx = qx.to(memory_format=torch.channels_last)

RuntimeError: false INTERNAL ASSERT FAILED at "/data/users/dzdang/pytorch/aten/src/ATen/quantized/Quantizer.cpp":430, please report a bug to PyTorch. cannot call qscheme on UnknownQuantizer
```
This occurred because of https://github.com/pytorch/pytorch/pull/75540/files#diff-d4df180433a09071e891d552426911c227b30ae9b8a8e56da31046e7ecb1afbeL79-L81 where `r` is created using `at::empty` and the information from `self`, a quantized tensor. This results in `r` being a quantized tensor, but with an `UnknownQuantizer`.

The current code uses `at::empty_like` to create `r`, which gets routed to `empty_like_quantized`, which gives `r` the same quantizer as `self`.

Test Plan:
python test/test_quantization.py -k test_qtensor_to_memory_format

python test/test_quantization.py -k test_qtensor_to_memory_format

Differential Revision:
D35516418
D35516418

Reviewed By: jerryzh168

Pulled By: dzdang

fbshipit-source-id: fc1a9987a8532c507835b3898c6508e6c56086d5