[MPS] fix failing conv test on main (#185978)
#184241 made this test device-generic, so it now runs on MPS, which fails with:
```
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/185978
Approved by: https://github.com/malfet