Update base for Update on "[dtensor][cp] experiment: call flex_attention on DTensor"
```
  File "/data/users/xilunwu/oss/pytorch/torch/_higher_order_ops/flex_attention.py", line 459, in flex_attention_fake_impl
    out = _permute_strides(out, query.stride())
  File "/data/users/xilunwu/oss/pytorch/torch/_higher_order_ops/flex_attention.py", line 70, in _permute_strides
    new_out = out.new_empty(out.shape).as_strided(out.shape, out_strides)
  File "/data/users/xilunwu/oss/pytorch/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
  File "/data/users/xilunwu/oss/pytorch/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
  File "/data/users/xilunwu/oss/pytorch/torch/distributed/tensor/_api.py", line 348, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/data/users/xilunwu/oss/pytorch/torch/distributed/tensor/_dispatch.py", line 174, in dispatch
    self.sharding_propagator.propagate(op_info)
  File "/data/users/xilunwu/oss/pytorch/torch/distributed/tensor/_sharding_prop.py", line 207, in propagate
    OutputSharding, self.propagate_op_sharding(op_info.schema)
  File "/data/users/xilunwu/oss/pytorch/torch/distributed/tensor/_sharding_prop.py", line 47, in __call__
    return self.cache(*args, **kwargs)
  File "/data/users/xilunwu/oss/pytorch/torch/distributed/tensor/_sharding_prop.py", line 456, in propagate_op_sharding_non_cached
    raise NotImplementedError(
torch._dynamo.exc.InternalTorchDynamoError: NotImplementedError: Operator aten.as_strided.default does not have a sharding strategy registered.
```


cc H-Huang awgu kwen2501 wanchaol fegin fduwjj wz337 wconstab d4l3k c-p-i-o

[ghstack-poisoned]