[release/2.5] Move to magma public github repo (#2193)
- Changed to support new Hipblas 3.0.0 which is part of ROCm 7.0 is
done.

CP of
https://github.com/ROCm/pytorch/commit/ec0c539336f1afff62279d24a8c945dadd4890eb
Validation:
http://rocm-ci.amd.com/job/mainline-pytorch2.5-manylinux-wheels/365/:
Magma built successfully, but build failed later with different error:
`[2025-05-27T18:52:28.154Z]
/pytorch/aten/src/ATen/hip/tunable/GemmHipblaslt.h:29:11: error:
‘hipblasDatatype_t’ does not name a type; did you mean
‘hipblasDiagType_t’?` which was addressed by
https://github.com/ROCm/pytorch/pull/2205

---------

Co-authored-by: Pruthvi Madugundu <pruthvigithub@gmail.com>