Fixed compiling on macOS 12 with SDK from 13
The current version of Xcode for macOS 12.6.3 is using SDK for macOS 13 that leads to an error like:
```
error: redefinition of 'MPSGraphResizeNearestRoundingMode'
```

To prevent that a condition here should use `MAC_OS_X_VERSION_MAX_ALLOWED` instead of `MAC_OS_X_VERSION_MIN_REQUIRED` that allows to track the used SDK, and not OS.

Value on macOS 13 with SDK 13:
```
MAC_OS_X_VERSION_MIN_REQUIRED: 130000
MAC_OS_X_VERSION_MAX_ALLOWED: 130100
```
and on macOS 12 with SDK 13:
```
MAC_OS_X_VERSION_MIN_REQUIRED: 120000
MAC_OS_X_VERSION_MAX_ALLOWED: 130100
```

I've also changed code to numeric version that fixed build on SDK which has no idea about macOS 13 :)