Update on "[wip] torch.Assert: attempt to make scriptable"
Summary:

Currently `torch.Assert` is not scriptable, which makes it not very useful for production code.  According to @jamesr66a , moving this to c++ op land will help with scriptability.  It's not 100% there yet, needs some review before further progress.

Current status:
```
# asserting things still works

(pytorch) [vasiliy@devgpu108.ash6 ~/local/pytorch] python test/test_utils.py TestAssert
Couldn't download test skip set, leaving all tests enabled...
.
----------------------------------------------------------------------
Ran 1 test in 0.178s

OK

# the overrides no longer work, TODO figure out why

(pytorch) [vasiliy@devgpu108.ash6 ~/local/pytorch] python test/test_fx.py TestFX.test_symbolic_trace_assert
Couldn't download test skip set, leaving all tests enabled...
E
======================================================================
ERROR: test_symbolic_trace_assert (__main__.TestFX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_fx.py", line 734, in test_symbolic_trace_assert
    traced = symbolic_trace(m)
  File "/data/users/vasiliy/pytorch/torch/fx/symbolic_trace.py", line 215, in symbolic_trace
    return GraphModule(root if isinstance(root, torch.nn.Module) else torch.nn.Module(), Tracer().trace(root
))
  File "/data/users/vasiliy/pytorch/torch/fx/symbolic_trace.py", line 199, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "test/test_fx.py", line 729, in forward
    torch.Assert(x.shape[1] > 4, message)
TypeError: Assert(): argument 'condition' (position 1) must be bool, not Proxy

```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D24740727](https://our.internmc.facebook.com/intern/diff/D24740727)

[ghstack-poisoned]