[SymmMem] Also use `get_window_offset` in `all_gather_offset` (#195516)
seems to be a missed change from https://github.com/pytorch/pytorch/pull/189088

otherwise we see failures in e.g.,

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_distributed.py", line 2198, in wrapper
    raise deferred_exception
RuntimeError: Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_distributed.py", line 1957, in _worker_loop
    cls._run_test_given_id(test_id)
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_distributed.py", line 1910, in _run_test_given_id
    test_fn(**kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_distributed.py", line 2201, in wrapper
    fn()
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 3886, in wrapper
    method(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 754, in instantiated_test
    test(self, **param_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_distributed.py", line 315, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/pytorch/test/distributed/test_nccl.py", line 1090, in test_all_gather_offset
    self.assertEqual(
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 4936, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Tensor-likes are not close!

Mismatched elements: 64 / 64 (100.0%)
Greatest absolute difference: 11.0 at index (0,) (up to 1e-05 allowed)
Greatest relative difference: 1.0 at index (0,) (up to 0.016 allowed)
rank 0: param 0 from src rank 0 mismatch

To execute this test, run the following from the base repo dir:
    python test/distributed/test_nccl.py NCCLSymmetricMemoryTest.test_all_gather_offset_split_sizes0_explicit_offsets_False_bfloat16
    ```

authored with codex
Pull Request resolved: https://github.com/pytorch/pytorch/pull/195516
Approved by: https://github.com/Skylion007, https://github.com/d4l3k