catching the correct exception (#100259)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/100259

somehow in distributed_c10d.py StoreHandlerTimeoutError is not getting converted to RuntimeException. instead of catching RuntimeException, we are not catching the correct exception so no conversion is necessary.
we are seeing the following line
torch.fb.rendezvous.zeus_lib.StoreHandlerTimeoutError: [fbcode/caffe2/caffe2/fb/distribute/lib/ZeusStoreHandler.cpp:237] Wait timeout for name(s): default_pg/store_based_barrier_key:1:last_worker
in the runs but if you look carefully in the code, this exception should be caught in caffe2/torch/distributed/distributed_c10d.py:496 as RuntimeError. Somehow the StoreHandlerTimeoutError is not getting caught as such. This could be due to loading multiple, replicated definitions of the error in pybindings, the code is peppered with these or some other reason. again, we are catching the direct error instead of its base class.
the code is linking with caffe2/torch/distributed/elastic/rendezvous/fb/zeus.cpp which also defines the ZeusStoreHandlerError but does not define it as RuntimeError which may be the source of the trouble as the initialization of pybind is nondeterministic. the correct definition is in fbcode/caffe2/torch/fb/rendezvous/zeus.cpp

Test Plan: regular tests & multiple tests of 'flow-cli clone f431528892 --run-as-secure-group ai_user_understanding' for various flows

Differential Revision: D45323074

fbshipit-source-id: f9b0e582ed9133770282d6bc4acba8f3217fd4b4