Update base for Update on "[inductor] make non-trivial tile ranges unbacked symint aware"
### Stacktrace
```
# If no fallback is provided then we'd see this.
  File "/data/users/colinpeppler/pytorch/torch/_inductor/codegen/simd.py", line 1746, in tile_ranges
    if V.graph.sizevars.atomically_apply_size_hint(
  File "/data/users/colinpeppler/pytorch/torch/_inductor/sizevars.py", line 653, in atomically_apply_size_hint
    size_dict = {
  File "/data/users/colinpeppler/pytorch/torch/_inductor/sizevars.py", line 654, in <dictcomp>
    symbol: V.graph.sizevars.size_hint(symbol, fallback=fallback)
  File "/data/users/colinpeppler/pytorch/torch/_inductor/sizevars.py", line 556, in size_hint
    return int(out)
  File "/home/colinpeppler/local/miniconda3/envs/pytorch/lib/python3.10/site-packages/sympy/core/expr.py", line 307, in __int__
    raise TypeError("Cannot convert symbols to int")
torch._inductor.exc.InductorError: TypeError: Cannot convert symbols to int
```

### Context
When unbacked symint is in the ranges, Inductor will choke up because either: 
1. no size hint exists or 
2. it can't statically evaluate an expression.

### Approach
- For (1), use unbacked symint fallback; this isn't optimal and we could do better on choosing a fallback
- For (2), use `statically_known*` mechanisms

xref: https://fb.workplace.com/groups/1028545332188949/permalink/1178385333871614/




cc voznesenskym penguinwu EikanWang jgong5 Guobing-Chen XiaobingSuper zhuhaozhe blzheng wenzhe-nrv jiayisunx ipiszy chenyang78 kadeng muchulee8 amjames chauhang aakhundov

[ghstack-poisoned]