Set the C++ standard on the exported CMake target.
This is needed so that downstream targets inherits the c++20 requirement. Without it it fails with for example:

pytorch/torch/include/ATen/core/TensorBase.h:1041:5: note: ‘requires’ only available with ‘-std=c++20’ or ‘-fconcepts’
pytorch/torch/include/ATen/core/TensorBase.h:1044:5: error: ‘requires’ does not name a type
1044 |     requires std::is_same_v<T, int64_t>
     |     ^~~~~~~~