Update on "[pytorch][rpc] add exception handling in enqueueSend"
in `ProcessGroupAgent::enqueueSend`, exceptions on the caller side can result in the RPC blocking forever, since the future is never marked as finished. This diff adds exception handling into `enqueueSend` so that the future is marked as completed with an exception, preventing this. See https://github.com/pytorch/pytorch/issues/25516, for more context. 

Note: exceptions on the callee side (such as calling a function with an invalid # of arguments) are already handled in the callback function that is executed on the callee side.

Test plan: Run the following script:

```
#!/usr/bin/env python
import os
import time
from datetime import timedelta
import torch
import torch.distributed as dist
from torch.multiprocessing import Process
import torch.distributed.rpc as rpc

def run(rank, size):
    if rank == 0:
        time.sleep(0.5) # to allow the other process to exit without joining
        ret = rpc.rpc_async("worker1", torch.add, args=(torch.ones(2), 2))
        result = ret.wait()

def init_process(rank, size, fn, backend='gloo'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29509'
    dist.init_process_group(backend, rank=rank, world_size=size, timeout=timedelta(seconds=12))
    rpc.init_model_parallel("worker{}".format(rank))
    fn(rank, size)
    if rank == 0: rpc.join_rpc()


if __name__ == "__main__":
    size = 2
    processes = []
    for rank in range(size):
        p = Process(target=init_process, args=(rank, size, run))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
```

Previously, this code would hang until the timeout passed into `init_process_group` was hit, and we'd see an error such as `RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:119] Timed out waiting 1800000ms for send operation to complete`. (note that this is not the original exception, which was lost)

With this patch, the exception is caught and passed up:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../dist_examples/run.py", line 27, in init_process
    fn(rank, size)
  File "../dist_examples/run.py", line 17, in run
    result = ret.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [2401:db00:12:918c:face:0:1d:0]:1966
```

The added unit test simulates this behavior.

Differential Revision: [D17416185](https://our.internmc.facebook.com/intern/diff/D17416185/)

[ghstack-poisoned]