inductor: fix failure in test_flex_decoding on <sm80
The test fails due to undefined variable:

```
Running inductor/test_flex_decoding 1/1 ...
SCRIBE_GRAPHQL_ACCESS_TOKEN is NOT set
Executing ['/opt/app-root/bin/python', '-bb', 'inductor/test_flex_decoding.py', '-m', 'not serial', '--shard-id=1', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '-x', '--reruns=2'] ...
Running inductor/test_fxir_backend 1/1 ...
SCRIBE_GRAPHQL_ACCESS_TOKEN is NOT set
Executing ['/opt/app-root/bin/python', '-bb', 'inductor/test_fxir_backend.py', '-m', 'not serial', '--shard-id=1', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '-x', '--reruns=2'] ...
/opt/app-root/lib64/python3.12/site-packages/torch/__init__.py:1613: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at /root/pytorch/aten/src/ATen/Context.cpp:80.)
  _C._set_float32_matmul_precision(precision)
Traceback (most recent call last):
  File "/root/pytorch/test/inductor/test_flex_decoding.py", line 309, in <module>
    class TestFlexDecoding(InductorTestCase):
  File "/root/pytorch/test/inductor/test_flex_decoding.py", line 751, in TestFlexDecoding
    @unittest.skipIf(SKIP_UT_ON_CPU, "Skip on CPU as not supported")
                     ^^^^^^^^^^^^^^
NameError: name 'SKIP_UT_ON_CPU' is not defined
```