removing allow_tf32 from pytorch inductor (#173731)
fixes #166387

As pytorch moved to [new API](https://docs.pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices) for tf32, many like transformer started using them.

It seems pytorch inductor is still using old allow_tf32, so when new API is invoked and read happens for old API we see error like
ERROR: PyTorch is checking whether allow_tf32_new is enabled for cuBlas matmul,Current status indicate that you have used mix of the legacy and new APIs to set the TF32 status for cublas matmul. We suggest only using the new API to set the TF32 flag. See also: https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices

My PR is addressing this by using new API in inductor.

currently I have only made changes pytorch issue lined above and transofrmer, you can see traceback in [comment](https://github.com/huggingface/transformers/issues/42371#issuecomment-3730137367) section here, https://github.com/huggingface/transformers/issues/42371

Can I can start changing more allow allow_tf32 in inductor

Pull Request resolved: https://github.com/pytorch/pytorch/pull/173731
Approved by: https://github.com/jansel, https://github.com/isuruf

Co-authored-by: Isuru Fernando <isuruf@gmail.com>