[xpu][fix] Fix test_wrap_triton_handled_during_tracing on XPU (#171512)
# Motivation
This PR aims to fix the failure introduced from https://github.com/pytorch/pytorch/pull/171289 on XPU backend.
Currently, some UTs under `test/dynamo/` are device-agnostic. So the cuda-specific code will raise the following error on XPU backend.
```python
AssertionError: Torch not compiled with CUDA enabled
```

# Additional Context
Fix https://github.com/pytorch/pytorch/issues/171508 and https://github.com/pytorch/pytorch/issues/171509

Pull Request resolved: https://github.com/pytorch/pytorch/pull/171512
Approved by: https://github.com/ezyang