remove special casing for sparse CSR shape comparison (#75593)
Summary:
Fixes https://github.com/pytorch/pytorch/pull/74264#discussion_r845780445.

The shape check works with or without the extras added in #74264.

```py
>>> a = torch.rand(2, 2).to_sparse_csr()
>>> b = torch.rand(2, 3).to_sparse_csr()
>>> torch.testing.assert_close(a, b)
AssertionError: The values for attribute 'shape' do not match: torch.Size([2, 2]) != torch.Size([2, 3]).
```

Tensor comparison is split into two parts:

1. Attribute comparison.
2. Value comparison.

https://github.com/pytorch/pytorch/blob/bcf6974c207ac0339bfb8bdfdb0b0ec348f7a22f/torch/testing/_comparison.py#L611-L616

The attribute comparison happens in

https://github.com/pytorch/pytorch/blob/bcf6974c207ac0339bfb8bdfdb0b0ec348f7a22f/torch/testing/_comparison.py#L618

The check for the matching shape

https://github.com/pytorch/pytorch/blob/bcf6974c207ac0339bfb8bdfdb0b0ec348f7a22f/torch/testing/_comparison.py#L647-L648

is one of the few checks that cannot be disabled through keyword arguments. Thus, there is no need for this check in `_compare_sparse_csr_values` since the comparison will fail before if the shapes mismatch.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/75593
Approved by: https://github.com/cpuhrsch

Test Plan: contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/8a053e387ececaf5cf5bf41a5b19e2e7487cfbf5

Reviewed By: b0noI

Differential Revision: D35561585

fbshipit-source-id: b13288ce3c13cd342cc3a8a5d78b497d2e513426