Disable fa4 on SM 12.0
Following https://github.com/pytorch/pytorch/blob/e41371ce/torch/nn/attention/_fa4.py#L110-L111
```
RuntimeError: FA4 flash_attention forward unsupported: FA4 requires compute capability 9.0 or 10.0
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>