Improve finding and using the rocm_version.h
On Fedora, the rocm_version.h's path is /usr/include/rocm_version.h
So we have this build error
pytorch/aten/src/ATen/hip/tunable/Tunable.cpp:40:10: fatal error:
  rocm-core/rocm_version.h: No such file or directory
   40 | #include <rocm-core/rocm_version.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

In other cases, depending on the rocm release either
/opt/rocm/include or /opt/rocm/include/rocm-core

Convert the EXISTS() checks into a find_path.
Add a -I${ROCM_VERSION_DIR} to the compile options so it can be
found by Tunable.cpp

Signed-off-by: Tom Rix <Tom.Rix@amd.com>