[release/2.7] Fix for flex attention tuning (#2589)
Bug fix after https://github.com/ROCm/pytorch/pull/2392 landed

Issue caused from bad merge conflict resolution, resulting in the code
using an outdated API.
> torch._inductor.exc.LoweringException: NameError: name
'_get_default_config_bwd' is not defined
  target: flex_attention_backward
  
 Models now run to completion