[dynamo] Fix Tensor Metadata Propagation for In-Place Ops (#167583)
Fixes #161275

Introduces `TensorVariable._propagate_inplace_metadata` to propagate tensor metadata for inplace ops correctly. This is done by reusing the change introduced in https://github.com/pytorch/pytorch/pull/161036/files#r2288498099 for setitem, but for all ops ending in "_" instead.

**Test Plan:** Added the `test/dynamo/test_dynamo_ops.py` test file, with the `TestTensorMetaProp.test_inplace_ops_propagate_requires_grad_metadata` test case. This uses a `CustomAutograd` to verify tensor metadata is propagated the same in eager and compiled (with eager backend). Without the fix, the test results in the following error.

```
======================================================================
ERROR: test_inplace_ops_propagate_requires_grad_metadata_add_cuda_float64 (__main__.TestTensorMetaPropCUDA.test_inplace_ops_propagate_requires_grad_metadata_add_cuda_float64)
Test that inplace ops from OpInfo propagate requires_grad correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_device_type.py", line 1151, in test_wrapper
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/arshzahed/pytorch/test/dynamo/test_dynamo_ops.py", line 3121, in test_inplace_ops_propagate_requires_grad_metadata
    self.assertEqual(
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_utils.py", line 4255, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not close!

Expected -6.649254588811632 but got -13.298509177623265.
Absolute difference: 6.649254588811632 (up to 1e-07 allowed)
Relative difference: 1.0 (up to 1e-07 allowed)
add: Output mismatch indicates metadata not propagated during tracing (issue #161275)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_utils.py", line 3300, in wrapper
    method(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_utils.py", line 3300, in wrapper
    method(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_utils.py", line 1707, in wrapper
    fn(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/testing/_internal/common_device_type.py", line 1163, in test_wrapper
    raise e_tracked from e
Exception: Scalars are not close!

Expected -6.649254588811632 but got -13.298509177623265.
Absolute difference: 6.649254588811632 (up to 1e-07 allowed)
Relative difference: 1.0 (up to 1e-07 allowed)
add: Output mismatch indicates metadata not propagated during tracing (issue #161275)

Caused by sample input at index 10: SampleInput(input=Tensor[size=(5, 5), device="cuda:0", dtype=torch.float64], args=TensorList[Tensor[size=(5, 5), device="cuda:0", dtype=torch.float64]], kwargs={'alpha': '-3.125'}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
    PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=10 python test/dynamo/test_dynamo_ops.py TestTensorMetaPropCUDA.test_inplace_ops_propagate_requires_grad_metadata_add_cuda_float64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/167583
Approved by: https://github.com/Lucaskabela, https://github.com/xmfan