Fix check for missing 'vst1q_f32_x2'
Previous fix was not complete:

/opt/rh/devtoolset-9/root/usr/bin/cc   -fopenmp -DNDEBUG -DHAS_VST1 -fPIE   -o CMakeFiles/cmTC_1e304.dir/src.c.o   -c /var/tmp/workspace/pytorch/build/CMakeFiles/CMakeTmp/src.c
/var/tmp/workspace/pytorch/build/CMakeFiles/CMakeTmp/src.c: In function ...main...:
/var/tmp/workspace/pytorch/build/CMakeFiles/CMakeTmp/src.c:6:16: error: ...a... undeclared (first use in this function)
    6 |   vst1q_f32_x2(a, v);
      |                ^
/var/tmp/workspace/pytorch/build/CMakeFiles/CMakeTmp/src.c:6:16: note: each undeclared identifier is reported only once for each function it appears in
gmake[1]: *** [CMakeFiles/cmTC_1e304.dir/src.c.o] Error 1
gmake[1]: Leaving directory `/var/tmp/workspace/pytorch/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_1e304/fast] Error 2