[Autograd] The behavior of Tensor.requires_grad=True is different from that of Tensor.requires_grad_(True).
As the title stated.

```Python
>>> a = torch.randn(3, 3, device="cpu", requires_grad=True)
>>> b = torch.pow(a, 2)
>>>
>>> b.requires_grad=False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().
>>> b.requires_grad=True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: you can only change requires_grad flags of leaf variables.

>>> b.requires_grad_(False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().
>>> b.requires_grad_(True)
tensor([[4.1244, 3.3084, 0.1038],
        [0.3303, 0.0662, 0.1792],
        [0.0080, 0.0127, 0.4904]], grad_fn=<PowBackward0>)
```

ghstack-source-id: 4e340a7402d2b6c5fd1e6be8129b936945089e0a
Pull-Request-resolved: https://github.com/pytorch/pytorch/pull/163263