better error message fix (#86422)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/86422

A user had a problem with fx-scripting and the error message can be improved.

Error was shown as:

RuntimeError: Keys for dictionaries used as an argument cannot contain a Node. Got key: {k}

which is obvious not quite helpful.

Test Plan:
Test in a notebook:
{F778667593}

Reviewed By: xunnanxu, SherlockNoMad

Differential Revision: D40157518

fbshipit-source-id: b7d6d7d48589beb708fd9fd3c0b127a081105379