[ATen][rocm] fix type issue
Summary:
Fixes a nightly build failure at AMD.

Originally,
```
std::initializer_list<int64_t> size = { param_size * num_linear_layers / 2, 1};
```
but https://github.com/pytorch/pytorch/pull/71925 changes as follows.
```
const auto size = { static_cast<int64_t>(bias_size * num_linear_layers / 2), 1L};
```

This caused a problem as follows (with a certain compiler):
```
/pytorch/aten/src/ATen/native/miopen/RNN_miopen.cpp:356:108: error: no matching function for call to 'at::Tensor::set_(const c10::Storage&, size_t&, const std::initializer_list<const long int>&)'
```

This patch reverts the type of `size`.
```
std::initializer_list<int64_t> size = { static_cast<int64_t>(bias_size * num_linear_layers / 2), 1L};
```

(Note: please let me explcitly cast the first variable (`bias_size * num_linear_layers / 2`) to avoid signed/unsigned type conversion warning. It should not cause any issue.)

Test Plan: CI

Differential Revision: D34153890

fbshipit-source-id: 953cc3e71289bbae419470f1173975be98f73d37