Add meta kernels for dequantize_per_tensor and quantize_per_tensor
Summary:
We're currently missing meta kernels for quantize_per_tensor and dequantize_per_tensor. When tracing models with dynamo i was running into failures due to these missing meta kernels if the integers passed into these function calls are SymInt's:

```
RuntimeError: buck-out/v2/gen/fbcode/346db10ce50cfaa6/caffe2/__gen_aten__/out/RegisterCompositeExplicitAutograd.cpp:1164: SymIntArrayRef expected to contain only concrete integers
```

Test Plan:
Test repro used:
```
def test_fn(x,b,c):
    a = torch.ops.quantized_decomposed.quantize_per_tensor.default(x, 0.1, 0, b, c, torch.int8)
    return a
```

Tracing this with the edge export flow causes failures as described above. Adding these missing meta kernels fixes the issue.

Differential Revision: D44046306

fbshipit-source-id: cfaaaac5d50add6022933d52a09c45ecea8d5b20