[reland] c10d: convert NanCheck to an op + tests (#174736) (#174990)
Summary:

This converts NanCheck into an op so it can be used from outside of ProcessGroupNCCL. This can be used from torchcomms.

Misc changes:
* add CPU implementation
* use CUDA_KERNEL_ASSERT macro so it logs a more helpful message when nancheck fires


Reland since https://github.com/pytorch/pytorch/pull/174736 was reverted

Test Plan:
contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/ffe476d1bfe408e9b34fd73d214aff790c9dea09

Test plan from GitHub:
CI

```
$ python -c "import torch; torch.ops.c10d.check_for_nan(torch.tensor(float('nan'), device='cuda')); torch.cuda.synchronize()"                 (pytorch-3.12)
/home/tristanr/pytorch/torch/csrc/distributed/c10d/NanCheck.cu:217: checkForNaN: block: [0,0,0], thread: [0,0,0] Assertion `!isnan(tailPtr[threadIdx.x])` failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tristanr/pytorch/torch/cuda/__init__.py", line 1165, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: device-side assert triggered
Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Reviewed By: kapilsh, dcci

Differential Revision: D93267474