[Static Runtime] Block linalg_svdvals codegen & run codegen script (#85983)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/85983

The test is causing issues:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
    graph(%A: Tensor, %driver: str?):
        %bias: None = prim::Constant()
        %ret = aten::linalg_svdvals(%A, %driver)
               ~~~~ <--- HERE
        %cloned = aten::clone(%ret, %bias)
        return (%cloned)
RuntimeError: torch.linalg.svd: keyword argument `driver=` is only supported on CUDA inputs with cuSOLVER backend.
```

Just block the op and re-run the codegen script to remove everything and update the generated ops.

Test Plan: Existing tests

Reviewed By: xuzhao9, tenpercent

Differential Revision: D39973860

fbshipit-source-id: 65e636832b75b409f97a527bc5425e7fc15ba294