[TorchElastic] handle EADDRINUSE message of libuv
The libuv backend has been set as the default TCPStore server
backend. The EADDRINUSE message of libuv is "address already in use"
instead of "Address already in use" as shown by the following error
message.

torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 23456, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use

Reproducer of the error msg:

import torch.distributed as dist

s1 = dist.TCPStore("127.0.0.1", 23456, 1, True)
s2 = dist.TCPStore("127.0.0.1", 23456, 1, True)

Fixes #191560