Revert "hip mappings"
This reverts commit 5237974a9bc3ec105b46fe2a18904a95ca3a414e.

CI fails with errors like:

`error: use of undeclared identifier 'hipEventWaitExternal'`

Apparently the rocm version usd in CI is not new enough.