Update base for Update on "Hashing for constant and singleton SymInt/SymBool"
Previously:
- SymNode can already be hashed because __eq__ is not implemented, so Python falls back to some kind of id-based hash. 
- SymBool also has the same id-based hash for the same reason.
- Because SymBool does not implement __eq__ either, equality checks that falls back to the id-based check as well, i.e. `b == True` or `b == c` would be False (even if b, c are both False)
- SymInt raises TypeError "unhashable type"

In this PR:
- Add the ability for SingletonSymInt to be hashed
- Continue to raise TypeError when non-singleton SymInt is hashed
- constant SymBool hashes and performs equality checks as if it were a Python bool (I don't know if we can rely on Python bool always hashing to 0 or 1)
- preserve existing behavior for non-constant SymBool and SymNode hashing

[ghstack-poisoned]