reorder cpuinfo and clog deps in TorchConfig.cmake (#79551) (#79551)
Summary:
cpuinfo has some symbols that need to be resolved with clog.
```

Static builds fail without this fix with this error:
api.c:(.text+0xc2): undefined reference to `clog_vlog_fatal'
init.c:(.text+0x19d1): undefined reference to `clog_vlog_error'
processors.c:(.text+0x551): undefined reference to `clog_vlog_error'
smallfile.c:(.text+0x172): undefined reference to `clog_vlog_error'

```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/79551
Approved by: https://github.com/malfet

Test Plan: contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/e3135946b220ed3f9bc3be9d2d5941e4285c6bec

Reviewed By: malfet

Differential Revision: D37242149

Pulled By: malfet

fbshipit-source-id: 89738b74f0a7edb0032d067bfb0ebad85c77e87b