[fake tensor] register copy, copy_, slice_scatter handling
Normally, fake tensor assumes that inputs to ops must all have the same devices, with a few exceptions. That's not true for these three ops, which have the format op(self, other, ...) and where `other` is copied either into `self` or into a new tensor.

This PR registers special handling for these ops, specifying the devices explicitly instead of relying on the automatic device-merging logic.

For reference, this was the previous error:

```
Traceback (most recent call last):
  File "test/test_fake_tensor.py", line 627, in test_multi_device_slice_assign
    out = fn(x_f, y_f)
  File "test/test_fake_tensor.py", line 614, in fn
    self[:,::2] = other
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1174, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1409, in dispatch
    return self.wrap_meta_outputs_with_default_device_logic(r, func, args, kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1475, in wrap_meta_outputs_with_default_device_logic
    return tree_map(partial(wrap), r)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1492, in wrap
    ) = FakeTensor._find_common_device(func, args, kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1104, in _find_common_device
    tree_map(merge_devices, args)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1100, in merge_devices
    raise RuntimeError(
RuntimeError: Unhandled FakeTensor Device Propagation for aten.copy_.default, found two different devices cpu, cuda:0
```

[ghstack-poisoned]