Revert "[xpu][test] Port distributed checkpoint test cases on Intel GPU (#168921)"
This reverts commit 319d3ae75cf930a3e73a4223a48465c49f8a1cf9.

Reverted https://github.com/pytorch/pytorch/pull/168921 on behalf of https://github.com/yangw-dev due to sorry but seems like this break internal tests  dlrm/tests/amd:aps_dlrm_local_model_publish_test_on_amd due to AttributeError: partially initialized module 'triton' has no attribute 'language' (most likely due to a circular import)  ([comment](https://github.com/pytorch/pytorch/pull/168921#issuecomment-3755755311))