Revert "[DTensor] compute shape and offset for arbitrary _StridedShard (#168146)"
This reverts commit 08bfadf971742edf63d8e3eb16f151de0c9dc41b.

Reverted https://github.com/pytorch/pytorch/pull/168146 on behalf of https://github.com/yangw-dev due to failed internal tests  due to AttributeError: 'LocalIntNode' object has no attribute 'int_', please fix it and re-merge again ([comment](https://github.com/pytorch/pytorch/pull/168146#issuecomment-3571957707))