Update on "Assert that dtype promotion does not convert fake tensor to tensor and remove bad double fake tensor wrapping"
testing a theory for fixing https://github.com/pytorch/pytorch/issues/118790

The code reverted in this diff was introduced in https://github.com/pytorch/pytorch/pull/104689

The PR above claims added a comment that claims "In case of dtype promotion, faketensor converted into tensor"
the path above results in trying to wrap a fake tensor with a fake tensor resulting and an error
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_method to(*(FakeTensor(..., size=(2,)), 'meta'), **{}):
Creating a new Tensor subclass FakeTensor but the raw Tensor object is already associated to a python object of type FakeTensor
```

I debugged and did not see that type promotion is changing a fake tensor to a tensor, I removed that code
and everything pass well with no failures, hence I added an assertion that if the input is fake tensor then type 
promotion is keeping it fake and removed that added call. 
```
Creating a new Tensor subclass FakeTensor but the raw Tensor object is already associated to a python object of type FakeTensor
```

if the input was originally fake tensor and output has become non fake, then we wrap output with input device?





[ghstack-poisoned]