make functional tensor not depend on inductor config.
Summary:
This is the third issue with having this dependency all of the issues were around is_fbcode.
the current failure is
```
AttributeError: partially initialized module 'torch' has no attribute 'version' (most likely due to a circular import)
```
those failure have been going on since  D62215095 landed.
to easily mitigate for now just moving the config to somewhere else.

Test Plan: buck test multipy/runtime:test_deploy_embedded_cuda_interp_without_cuda_available -- --run-disabled TorchpyTest.AcquireMultipleSessionsInDifferentPackages

Differential Revision: D62614252