[ROCm] Bundle librocm_smi64.so for ROCm <= 7.2 wheels (#191450)
[Refiled version of #191366, but from personal fork, since pytorchbot merge wasn't working on that PR]

## Summary

PR #190014 migrated wheel repair from `librocm_smi64.so` to `libamd_smi.so` as part of the rocm_smi to amd_smi transition. ROCm 7.2 wheels still depend on `librocm_smi64.so`, so wheel repair fails when that library is not bundled.

The [latest ROCm7.2 binary test job from 07/28](https://github.com/pytorch/pytorch/actions/runs/30341928221/job/90282176024) shows that `librocm_smi64.so` is not bundled:
```
	librocm_smi64.so.1 => /opt/rocm-7.2.1/lib/librocm_smi64.so.1 (0x00007b4be5737000)
```

This shows up in downstream projects such as torchtitan CI: https://github.com/pytorch/torchtitan/actions/runs/30294524429/job/90072157024#step:16:474
```
from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: librocm_smi64.so.1: cannot open shared object file: No such file or directory
```

This change bundles the rocm-smi library based on `GPU_ARCH_VERSION`:
- ROCm <= 7.2: bundle `librocm_smi64.so`

## Test plan

- [x] ROCm 7.2 manywheel build completes wheel repair successfully, and [the binary test job](https://github.com/pytorch/pytorch/actions/runs/30409907599/job/90479153330?pr=191366) shows that librocm_smi64.so is being picked up from torch/lib installation path instead of /opt/rocm
```
	librocm_smi64.so => /opt/python/cp312-cp312/bin/../lib/python3.12/site-packages/torch/lib/librocm_smi64.so (0x00007fc6c1f5e000)
```

Authored with assistance from Cursor

Made with [Cursor](https://cursor.com)
Pull Request resolved: https://github.com/pytorch/pytorch/pull/191450
Approved by: https://github.com/wconstab

Co-authored-by: Cursor <cursoragent@cursor.com>