[Distributed] Enable support for reduce_scatter_base backward for XCCL backend (#168213)
Enable reduce_scatter_base backward support for XCCL  backends

With XPU it was resulting in below error

```
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 816, in run_test
    getattr(self, test_name)()
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 670, in wrapper
    fn()
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3224, in wrapper
    method(*args, **kwargs)
  File "/home/ssamuel/workspace/pytorch/test/distributed/test_c10d_spawn_nccl.py", line 193, in test_all_gather_base
    z.backward()
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/_tensor.py", line 625, in backward
    torch.autograd.backward(
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 354, in backward
    _engine_run_backward(
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/autograd/graph.py", line 841, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/autograd/function.py", line 315, in apply
    return user_fn(self, *args)
  File "/home/ssamuel/miniforge3/envs/env_borealis_2025_1.24_py_3_10/lib/python3.10/site-packages/torch/distributed/nn/functional.py", line 366, in backward
    raise RuntimeError("Backend not supported!")
RuntimeError: Backend not supported!

```

Previously the backward path for reduce_scatter_base was supported only for NCCL which caused runtime errors on XPU. This change implements the missing backward handling and unifies the behavior for XCCL backends.

Verified with XCCL; reduce_scatter_base backward now completes without errors.

Fixes #[intel/torch-xpu-ops#2369](https://github.com/intel/torch-xpu-ops/issues/2369)

Pull Request resolved: https://github.com/pytorch/pytorch/pull/168213
Approved by: https://github.com/EikanWang, https://github.com/albanD, https://github.com/guangyey