Update on "Improve torch.cond useability: Return UserError with actionable error messages"
It's part of the effort to improve PT2 Export UX. This PR is to improve the usability of `torch.cond()` by separating user errors from the dynamo internal errors. By definition, user error means the usage of `torch.cond()` violates the restrictions of this API therefore needs users to take action and fix the error.

In this notebook N3363227 we discovered a bunch of limitations of using `torch.cond(pred, true_fn, false_fn, operands)`. In summary, the limitations can be categorized as:
 - predicate restriction (`pred`)
 - operands restriction (`operands`)
 - branch restriction (`true_fn` & `false_fn`)

The error message will be more accurate about where the (user) error is from and more actionable for users to fix it.

For example, in general `true_fn` and `false_fn` (defined by users) must return a single tensor with exact same metadata, e.g. shape, dtype, etc.
if one branch returns a single tensor but the other branch return 2 tensors, user will see error message like:
```
torch._dynamo.exc.UserError: COND_OP_RESTRICTION. Expect true branch and false branch return with same length but got
  true_fn returns [sin]
  false_fn returns [x_1, x_1]
```
If both branches are returning a single tensor but with different shapes, user will see error message like:
```
torch._dynamo.exc.UserError: COND_OP_RESTRICTION. Expect each tensor returned from true branch and false branch has exact same metadata but got
  true_fn returns TensorMetadata(shape=torch.Size([4]), dtype=torch.float32, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})
  false_fn returns TensorMetadata(shape=torch.Size([10, 10]), dtype=torch.float32, requires_grad=False, stride=(10, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})
```

Another example about `operands`. In general, it must be a list of tensors and the signature of `true_fn` and `false_fn` must match with the `operands`.
If the operands contains non-tensor types, user will see error message like:
```
torch._dynamo.exc.UserError: COND_OP_RESTRICTION. Expect operands to be a list of tensors but got ["<class 'torch.Tensor'>", "<class 'float'>"]

from user code:
   File "~/pytorch/test/dynamo/test_export.py", line 2504, in f_non_tensor_operands
    return cond(True, lambda x, a: x.sin(), lambda x, a: x.cos(), [x, a])
```

cc soumith voznesenskym penguinwu anijain2305 EikanWang jgong5 Guobing-Chen XiaobingSuper zhuhaozhe blzheng Xia-Weiwen wenzhe-nrv jiayisunx desertfire

[ghstack-poisoned]