c10d: Don't add NCCL backend by default without CUDA
The NCCL backend requires CUDA (including devices) to be available.
So don't use that backend by default if that isn't the case to avoid the
following error when creating a CPU-only device mesh:
> RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

Fixes #117746