Remove unused var (ws_) and use vars in undefined case for compile
Summary:
I'm trying to get xplat/caffe2 compiling in ovrsource. I was running into undefined and unused private field compiler warnings and decided it would be easier to fix these then to add Wno equivalents of those flags into the caffe2 buck file.

```
 ✘ dxy@dxy-mbp  ~/ovrsource  buck build mode/android32/coretech/mac/dev-release //xplat/caffe2:caffe2
In file included from xplat/caffe2/caffe2/utils/signal_handler.cc:1:
xplat/caffe2/caffe2/utils/signal_handler.h:31:10: error: private field 'SIGINT_action_' is not used [-Werror,-Wunused-private-field]
  Action SIGINT_action_;
         ^
xplat/caffe2/caffe2/utils/signal_handler.h:32:10: error: private field 'SIGHUP_action_' is not used [-Werror,-Wunused-private-field]
  Action SIGHUP_action_;
         ^
xplat/caffe2/caffe2/utils/signal_handler.h:33:17: error: private field 'my_sigint_count_' is not used [-Werror,-Wunused-private-field]
  unsigned long my_sigint_count_;
                ^
xplat/caffe2/caffe2/utils/signal_handler.h:34:17: error: private field 'my_sighup_count_' is not used [-Werror,-Wunused-private-field]
  unsigned long my_sighup_count_;
                ^
4 errors generated.
command exited with code 1: third-party/toolchains/android-ndk/r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-android --sysroot third-party/toolchains/android-ndk/r18b/sysroot --gcc-toolchain=third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -D__ANDROID_API__=24 @/Users/dxy/ovrsource/buck-out/bin/xplat/caffe2/caffe2#compile-signal_handler.cc.oe8090f90,default/ppandcompile.argsfile -isystem third-party/toolchains/android-ndk/r18b/sysroot/usr/include/arm-linux-androideabi -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++/include -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++abi/include -isystem third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi
xplat/caffe2/caffe2/share/fb/stylizer/median_blur_ops.cc:593:14: error: private field 'ws_' is not used [-Werror,-Wunused-private-field]
  Workspace* ws_;
             ^
1 error generated.
command exited with code 1: third-party/toolchains/android-ndk/r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-android --sysroot third-party/toolchains/android-ndk/r18b/sysroot --gcc-toolchain=third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -D__ANDROID_API__=24 @/Users/dxy/ovrsource/buck-out/bin/xplat/caffe2/caffe2#compile-median_blur_ops.cc.o0cb98141,default/ppandcompile.argsfile -isystem third-party/toolchains/android-ndk/r18b/sysroot/usr/include/arm-linux-androideabi -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++/include -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++abi/include -isystem third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi
Building: finished in 4.9 sec (100%) 211/210 jobs, 2 updated
  Total time: 4.9 sec
More details at https://our.intern.facebook.com/intern/buck/build/774d0dc6-8e29-437f-97af-31a6f341991a
Command failed with exit code 1.
stderr: In file included from xplat/caffe2/caffe2/utils/signal_handler.cc:1:
xplat/caffe2/caffe2/utils/signal_handler.h:31:10: error: private field 'SIGINT_action_' is not used [-Werror,-Wunused-private-field]
  Action SIGINT_action_;
         ^
xplat/caffe2/caffe2/utils/signal_handler.h:32:10: error: private field 'SIGHUP_action_' is not used [-Werror,-Wunused-private-field]
  Action SIGHUP_action_;
         ^
xplat/caffe2/caffe2/utils/signal_handler.h:33:17: error: private field 'my_sigint_count_' is not used [-Werror,-Wunused-private-field]
  unsigned long my_sigint_count_;
                ^
xplat/caffe2/caffe2/utils/signal_handler.h:34:17: error: private field 'my_sighup_count_' is not used [-Werror,-Wunused-private-field]
  unsigned long my_sighup_count_;
                ^
4 errors generated.
command exited with code 1: third-party/toolchains/android-ndk/r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-android --sysroot third-party/toolchains/android-ndk/r18b/sysroot --gcc-toolchain=third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -D__ANDROID_API__=24 @/Users/dxy/ovrsource/buck-out/bin/xplat/caffe2/caffe2#compile-signal_handler.cc.oe8090f90,default/ppandcompile.argsfile -isystem third-party/toolchains/android-ndk/r18b/sysroot/usr/include/arm-linux-androideabi -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++/include -isystem third-party/toolchains/android-ndk/r18b/sources/cxx-stl/llvm-libc++abi/include -isystem third-party/toolchains/android-ndk/r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi
    When running <c++ preprocess_and_compile>.
    When building rule //xplat/caffe2:caffe2#compile-signal_handler.cc.oe8090f90,default.
```

Differential Revision: D15402928

fbshipit-source-id: 67d4535655ac10a4246372c19eab3c1896874cd9