[xpu][fix][Inductor] Catch Intel Triton compilation/runtime error as IntelGPUError.  (#169167)
This PR updates the pinned Intel Triton commit (based on the 3.7.x release) to introduce IntelGPUError, which is used to catch compilation and runtime errors. This allows Inductor to safely discard Triton configurations that are not suitable for Intel GPUs.

Background:
The test case python test/inductor/test_native_matmul.py -k test_3mm_add
produces the following error on XPU:
```
  File "/workspacetriton/python/triton/compiler/compiler.py", line 489, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills, self.n_max_threads = driver.active.utils.load_binary(
  File "/workspace/triton/python/triton/backends/intel/driver.py", line 217, in load_binary
    return self.shared_library.load_binary(args)
torch._inductor.exc.InductorError: RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```
This occurs for one of the Triton kernel configs that hits a hardware limitation, causing Triton’s C++ code to raise PyExc_RuntimeError when compiling the SPIR-V kernel. Intel Triton has catched such Cpp error and raised to Inductor as `IntelGPUError` so that we can safely discard the failing config and continue other configs.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169167
Approved by: https://github.com/jansel, https://github.com/EikanWang