skip embedding_bag since its backward is not compatible to cudagraph (#88874)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/88874

Work around that the bwd of embedding_bag doesn't work with cudagraph with the following error:

RuntimeError: unique_by_key: failed to synchronize: cudaErrorStreamCaptureUnsupported: operation not permitted when stream is capturing

and then cuda memory error

Differential Revision: D40625081

fbshipit-source-id: 8950bf123cb52b90d86179fea7d35b9d9c8935b7