Revert "remove override hint from size_hint, atomically_size_hint, and symbolic_hint (#172429)"
This reverts commit 19d8ad08cd8c6ee15c34117daaaea04d929778e4.

Reverted https://github.com/pytorch/pytorch/pull/172429 on behalf of https://github.com/yangw-dev due to sorry but it seems like this breaks internal test, error: AttributeError: 'ShapeEnv' object has no attribute 'var_to_val'. Did you mean: 'val_to_var'? ([comment](https://github.com/pytorch/pytorch/pull/172405#issuecomment-3760701401))