Remove unused `dim_plane` from reflection_pad2d_backward_out_template
Probably introduced by https://github.com/pytorch/pytorch/pull/102254

This fixes `variable 'dim_plane' set but not used ` on my clang-14.0.3 compiler complained about it:
```
/Users/nshulga/git/pytorch/pytorch/aten/src/ATen/native/ReflectionPad.cpp:272:7: error: variable 'dim_plane' set but not used [-Werror,-Wunused-but-set-variable]
  int dim_plane = 0;
      ^
1 error generated.
```