QNNPACK: q8gemm/8x8-dq-aarch64-neon.S fix mov operand for gcc
Unlike clang, GNU assembler does not support 4s on neon mov, so use 16b.

Fixes:

8x8-dq-aarch64-neon.S: Assembler messages:
8x8-dq-aarch64-neon.S:657:
Error: operand mismatch -- `mov V8.4s,V9.4s'
Info:    did you mean this?
Info:            mov v8.8b, v9.8b
Info:    other valid variant(s):
Info:            mov v8.16b, v9.16b

Signed-off-by: Edward Swarthout <Ed.Swarthout@nxp.com>