Migrate 2 test cases for xpu
Fix lint issue

Fix typo

Remove cpu relative changes for xpu

Fix lint issues

Remove _sleep for xpu

Add skip test case for _scatter not implemented in xpu and fix typo in get another xpu device method

Skip failed cases for xpu

Fix lint issue

Fix typo

Remove sleep test for xpu

Replace cuda with cpu

Fix thread_shutdown test case

Skip the failed test case test_autograd_multiple_dispatch_registrations due to tensor not closed

Change the skip if message

Change the skip if message

Remove the skip statements from the supported cases by xpu

Add issue id url and remove the skipifxpu for forward_mode_AD, only cuda not implenented the error

Apply lintrunner changes

Fix cpu failed case

Fix lint issue

Add skip test case

Fix lint issues

Update the ut file base on the xpu ops issues

Fix merge and rebase syntax errors

Roll back the changes which is not supported by xpu

Fix ut failure AttributeError: 'torch.device' object has no attribute 'memory_allocated'. get device module instead of using accelerator

Fix ut failure due to device doesn't have memory_allocated method

merge conflicts

generalize the ut changes with accelerator

Fix ut issues

change the skip as permanent

Merge the conflicts and rebase on main

Merge the conflicts with main

merge conflict

Fix lint issues

Update the ut file base on the xpu ops issues

Fix merge and rebase syntax errors

 Conflicts:
	test/test_autograd.py

Roll back the changes which is not supported by xpu

Fix ut failure AttributeError: 'torch.device' object has no attribute 'memory_allocated'. get device module instead of using accelerator

merge conflicts

Merge conflicts

Fix ut issues

change the skip as permanent

Merge the conflicts and rebase on main

Merge the conflicts with main