[Inductor] Fix lowmem_dropout() missing 1 required positional argument: 'p' (#88716)
Fixes error from 7k github models: https://github.com/jansel/pytorch-jit-paritybench/blob/master/generated/test_GuYuc_WS_DAN_PyTorch.py

Error:
```
TypeError: lowmem_dropout() missing 1 required positional argument: 'p'

While executing %lowmem_dropout : [#users=1] = call_function[target=torch._inductor.overrides.lowmem_dropout](args = (%avg_pool2d_9,), kwargs = {training: False})
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/88716
Approved by: https://github.com/ngimel, https://github.com/jansel, https://github.com/desertfire