Add setuptools and wheel to cp312, cp313 and cp313t for Manylinux2_28 builds (#139636)
Install setuptools and wheel dependencies for cp312, cp313, cp313t on Manylinux 2_28 images.
This should resolve
```
ModuleNotFoundError: No module named 'setuptools'
```
On PR: https://github.com/pytorch/pytorch/pull/138732

This issue was addressed on XPU images already. We should apply the same fix for the rest of the images instead of keeping it XPU specific.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/139636
Approved by: https://github.com/huydhn, https://github.com/chuanqi129