Bumping doc build instance type (#82740)
### Description
Bumping doc build instance type since we have constant failures in nightly docs build, running out of memory
Example:
https://github.com/pytorch/pytorch/runs/7642875300?check_suite_focus=true#step:8:26330
```
waiting for workers...
/home/ec2-user/actions-runner/_work/_temp/318122b1-3455-4a6b-bcb0-32b541662a5e.sh: line 28: 12686 Killed                  docker exec -t "${container_name}" bash -c "sudo chown -R jenkins . && pip install dist/*.whl && ./.circleci/scripts/${DOCS_TYPE}_doc_push_script.sh"
Error: Process completed with exit code 137.
```

### Testing
In CI

Pull Request resolved: https://github.com/pytorch/pytorch/pull/82740
Approved by: https://github.com/kit1980, https://github.com/janeyx99, https://github.com/seemethere