Prevent VS2017 from emitting ambiguous symbol errors
These std::forward calls cause VS2017 to emit:

error C2872: 'std': ambiguous symbol

This fix prevents the ambiguity by specifying that ::std is intended.