[fx2trt] Fix dummy weight initialization in conv1d converter (#78402)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/78402

X-link: https://github.com/pytorch/fx2trt/pull/84

att, currently it errors out with the following error:
```
---> 72         dummy_weight = trt.Weights(weight_shape)
     73         layer = network.add_convolution_nd(
     74             input=input_val,
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorrt.tensorrt.Weights(type: tensorrt.tensorrt.DataType = <DataType.FLOAT: 0>)
    2. tensorrt.tensorrt.Weights(a: numpy.ndarray)
```
full error: https://www.internalfb.com/phabricator/paste/view/P503598381
we need to pass arond a numpy ndarray instead of a shape here.

Test Plan:
```
buck test mode/opt deeplearning/trt/fx2trt_oss/test/converters:test_convolution
```

```
buck test mode/opt deeplearning/trt/fx2trt_oss/test/quant:test_quant_trt
```

Reviewed By: wushirong

Differential Revision: D36721313

fbshipit-source-id: 387c4db29d2d999b45448c5fcf4f791cc702940e