Fixes an endian swap bug on big endian machines. Endian conversion of the variable 'size' was forgotten in serialization.cpp. Throws an assertion in serialization.py on big endian machines.
Additionally the patch reads and writes torch files in the native
little endian format so that the model files are portable across x86 and s390.

Details:
A torch model file produced on x86 was loaded on to a big endian s390 arch machine.
The very large integer 2305843009213693952 is read with doRead() from file.
It should have been read as 32.  If you endian swap the large int it is actually 32

loaded_model = torch.load( opt.model_file, map_location=torch.device("cpu"))
File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 422, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 616, in _load
deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 2305843009213693952 got 32