profiler: Fix undefined reference to `unwind_c` in `unwind_entry` while LTO is enabled
With LTO(Link Time Optimization) enabled in CFLAGS, some compiler will optimize
and strip the unwind_c function, which is caused by compiler that couldn’t resolve
reference correctly, thus breaking the build with undefined reference in unwind_entry.
Add an attribute to avoid this bad situation.

Signed-off-by: GarfieldHan <2652609017@qq.com>