Empty cache in test_set_per_process_memory_fraction (#181605)
This test needs to be more robust because a previous test's behaviour can impact this test's behaviour.

A specific case where we ran into this situation is on gfx1101, where the test fails with

```
test/test_cuda.py::TestCuda::test_set_per_process_memory_fraction FAILED
[0.1163s]

Traceback (most recent call last):
  File "/var/lib/jenkins/pytorch/test/test_cuda.py", line 471, in test_set_per_process_memory_fraction
    tmp_tensor = torch.empty(application, dtype=torch.int8, device="cuda")
RuntimeError: Trying to create tensor with negative dimension -5681285432: [-5681285432]
```

This error is coming from an integer overflow when another unit test,
test/test_cuda.py::TestCuda::test_randint_generation_for_large_numel
creates a tensor with a huge numel, which overflows into a higher
torch.cuda.max_memory_reserved() when you call
test/test_cuda.py::TestCuda::test_set_per_process_memory_fraction
afterward. To avoid this we introduced torch.cuda.empty_cache() to clean up CUDA states.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/181605
Approved by: https://github.com/liangel-02, https://github.com/jeffdaily