[re_build] Get output from stdout and sterr in local and remote execution (#150375)
Summary:

Get output from stdout and sterr in local and remote execution.

For local, we just do `stdout=subprocess.PIPE` (same for stderr).

For remote, we need to use `re_client.get_stdout_stderr_bytes(result, metadata)` to get the `stderr` and `stdout` and return them. Note that `result.stderr_raw` is empty and does not get updated after `re_client.get_stdout_stderr_bytes` call.

Test Plan:
```
buck2 run mode/dev-nosan sigmoid/inference/ts_migration:pt2i_readiness_main -- --model_id  522655924 --test_suite ads_dsnn_prod --mode test_sub_module
```

```
error: Function _ZN5torch12aot_inductorL22__check_inputs_outputsEPP16AtenTensorOpaqueS3_ is too big to optimize [-Werror,-Wignored-optimization-argument]
2 warnings and 1 error generated.

The runtime check __check_inputs_outputs() is too big to optimize. Please use torch._inductor.config.aot_inductor.compile_wrapper_opt_level = 'O0' flag.
```


Remote builder error log:

```
E0331 17:53:24.071000 1470010 re_build_helper.py:308] Running ['/mnt/gvfs/third-party2/llvm-fb/1319cfc7ef7df48276e8bef38249926baa08e326/17/platform010/72a2ff8/bin/clang-17', 'czwz27iqa57ngqnswgyyg24f7oisvwoeyhdlcse3w2akuusfk3yn.wrapper.cpp', '-D', 'TORCH_INDUCTOR_CPP_WRAPPER', '-D', 'STANDALONE_TORCH_HEADER', '-D', 'C10_USING_CUSTOM_GENERATED_MACROS', '-D', 'CPU_CAPABILITY=AVX2', '-D', 'CPU_CAPABILITY_AVX2', '-D', 'HAVE_AVX2_CPU_DEFINITION', '-D', 'C10_USE_GLOG', '-D', 'C10_USE_MINIMAL_GLOG', '-D', 'C10_DISABLE_TENSORIMPL_EXTENSIBILITY', '-fPIC', '-O1', '-DNDEBUG', '-fno-trapping-math', '-funsafe-math-optimizations', '-ffinite-math-only', '-fno-signed-zeros', '-fno-math-errno', '-fno-finite-math-only', '-fno-unsafe-math-optimizations', '-ffp-contract=off', '-Wall', '-std=c++17', '-Wno-unused-variable', '-Wno-unknown-pragmas', '-Werror=ignored-optimization-argument', '-nostdinc', '-I/mnt/gvfs/third-party2/sleef/04504ce3d344bc68cbe6809aae1e3fbd8d62047f/trunk/platform010/dfaae0f/include', '-I/mnt/gvfs/third-party2/openmp/9cd77a14936e94ee99005ce4db7369bd8bf05df3/12/platform010/76ebdda/include', '-I/mnt/gvfs/third-party2/python/1a1e60db4daf6aed823cf4c653cadebdbf4511d2/3.10/platform010/9168809/include/python3.10', '-I/mnt/gvfs/third-party2/llvm-fb/1319cfc7ef7df48276e8bef38249926baa08e326/17/platform010/72a2ff8/lib/clang/17/include', '-I/mnt/gvfs/third-party2/libgcc/5df62019728dc785bba36d6e5b2a1fb81ca9f349/11.x/platform010/5684a5a/include/c++/trunk', '-I/mnt/gvfs/third-party2/libgcc/5df62019728dc785bba36d6e5b2a1fb81ca9f349/11.x/platform010/5684a5a/include/c++/trunk/x86_64-facebook-linux', '-I/mnt/gvfs/third-party2/libgcc/5df62019728dc785bba36d6e5b2a1fb81ca9f349/11.x/platform010/5684a5a/include/c++/trunk/backward', '-I/mnt/gvfs/third-party2/glibc/36dac9ed04ceabd409d33dde5a64aba02ac4967a/2.34/platform010/f259413/include', '-I/mnt/gvfs/third-party2/kernel-headers/0883cccda758e68b47e4c04e4fa01142e1f60f32/fb/platform010/da39a3e/include', '-Iinclude', '-I/usr/local/fbcode/platform010/include/python3.10', '-I/data/users/shangdiy/fbsource/buck-out/v2/gen/fbcode/4c4fa52cd141b421/sigmoid/inference/ts_migration/__pt2i_readiness_main__/pt2i_readiness_main#link-tree/torch/include', '-I/data/users/shangdiy/fbsource/buck-out/v2/gen/fbcode/4c4fa52cd141b421/sigmoid/inference/ts_migration/__pt2i_readiness_main__/pt2i_readiness_main#link-tree/torch/include/torch/csrc/api/include', '-I/tmp/torchinductor_shangdiy/a6', '-I/mnt/gvfs/third-party2/cuda/d5b5304892fcb9e672cba522b3ad7be55e82ff29/12.4/platform010/76ebdda/include', '--rtlib=compiler-rt', '-fuse-ld=lld', '-Wl,--script=script.ld', '-B/mnt/gvfs/third-party2/glibc/36dac9ed04ceabd409d33dde5a64aba02ac4967a/2.34/platform010/f259413/lib', '-L/mnt/gvfs/third-party2/glibc/36dac9ed04ceabd409d33dde5a64aba02ac4967a/2.34/platform010/f259413/lib', '-mavx2', '-mfma', '-mf16c', '-D_GLIBCXX_USE_CXX11_ABI=1', '-Wp,-fopenmp', '/mnt/gvfs/third-party2/openmp/9cd77a14936e94ee99005ce4db7369bd8bf05df3/12/platform010/76ebdda/lib/libomp.so', '-c', '-o', 'czwz27iqa57ngqnswgyyg24f7oisvwoeyhdlcse3w2akuusfk3yn.wrapper.o'] failed with result.exit_code=1, stdout_str='', stderr_str="clang-17: warning: -Wl,--script=script.ld: 'linker' input unused [-Wunused-command-line-argument]\nclang-17: warning: /mnt/gvfs/third-party2/openmp/9cd77a14936e94ee99005ce4db7369bd8bf05df3/12/platform010/76ebdda/lib/libomp.so: 'linker' input unused [-Wunused-command-line-argument]\nclang-17: warning: argument unused during compilation: '--rtlib=compiler-rt' [-Wunused-command-line-argument]\nclang-17: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]\nclang-17: warning: argument unused during compilation: '-L/mnt/gvfs/third-party2/glibc/36dac9ed04ceabd409d33dde5a64aba02ac4967a/2.34/platform010/f259413/lib' [-Wunused-command-line-argument]\nIn file included from czwz27iqa57ngqnswgyyg24f7oisvwoeyhdlcse3w2akuusfk3yn.wrapper.cpp:2:\nIn file included from include/torch/csrc/inductor/aoti_include/cpu.h:3:\nIn file included from include/torch/csrc/inductor/aoti_include/common.h:7:\nIn file included from include/torch/csrc/inductor/aoti_runtime/interface.h:7:\nIn file included from include/torch/csrc/inductor/aoti_runtime/utils.h:14:\nIn file included from include/torch/csrc/inductor/aoti_torch/c/shim.h:65:\nIn file included from include/c10/util/Half.h:59:\nIn file included from /mnt/gvfs/third-party2/llvm-fb/1319cfc7ef7df48276e8bef38249926baa08e326/17/platform010/72a2ff8/lib/clang/17/include/immintrin.h:646:\n/mnt/gvfs/third-party2/llvm-fb/1319cfc7ef7df48276e8bef38249926baa08e326/17/platform010/72a2ff8/lib/clang/17/include/amxcomplexintrin.h:139:13: warning: unused function '__tile_cmmimfp16ps' [-Wunused-function]\n  139 | static void __tile_cmmimfp16ps(__tile1024i *dst, __tile1024i src0,\n      |             ^~~~~~~~~~~~~~~~~~\n/mnt/gvfs/third-party2/llvm-fb/1319cfc7ef7df48276e8bef38249926baa08e326/17/platform010/72a2ff8/lib/clang/17/include/amxcomplexintrin.h:162:13: warning: unused function '__tile_cmmrlfp16ps' [-Wunused-function]\n  162 | static void __tile_cmmrlfp16ps(__tile1024i *dst, __tile1024i src0,\n      |             ^~~~~~~~~~~~~~~~~~\nerror: Function _ZN5torch12aot_inductorL22__check_inputs_outputsEPP16AtenTensorOpaqueS3_ is too big to optimize [-Werror,-Wignored-optimization-argument]\n2 warnings and 1 error generated.\n"
```

Reviewed By: bertmaher

Differential Revision: D72208338