[sparse] Fix semi-structured sparse shape mismatch bug
Summary:

Currently, PyTorch incorrectly calculates the size of the returned
matrix when we pass a non-contiguous batched (>2d) input to the
semi-structured sparse subclass.

This is most common in MLP layers, where we have 2 linear layers back to back.

This will lead to an error like the following:
```
RuntimeError: shape '[20, 64, 64, 3072]' is invalid for input of size
62914560

```
Where the size of the sparse matmul result is off by a factor of 4. I'm
not sure exactly where this bug comes from, but I traced it to [this](https://github.com/pytorch/pytorch/blob/01b2f25ebda85d307b27847ad67efe2b5bb54265/aten/src/ATen/native/LinearAlgebra.cpp#L1959) function.

Note that this error goes away in inference mode, since we avoid
decomposing the aten.linear op

This fix overload __torch_function, specifically for the F.linear op.
The goal is to implement our own folding to 2d / unfolding code so that
we can avoid running into this issue.

An alternative way to fix this issue is to set
TORCH_FLATTEN_LINEAR_3D=True, which will also fix this error.

Test Plan:
```
python test/test_sparse_semi_structured.py -k test_mlp

```

Reviewers:

Subscribers:

Tasks:

Tags:

[ghstack-poisoned]