Back out "Introduce discontinuity to nested tensor (#80981)"
Summary:
Original commit changeset: 1ed73f4e4783

Original Phabricator Diff: D38066963

D38066963 broke the master, so we failed to load the model with error: failed: std::runtime_error: Provided sample inputs are incorrect!

Test Plan:
With D38066963, we failed to the model.

```
I0725 21:17:39.218427 1090926 PyTorchPredictorContainer.cpp:2390] Start to warmup the predictor of the method "merge.forward"
I0725 21:17:39.409844 1090926 InferenceContext.h:48] Disabling warm up mode
E0725 21:17:39.409868 1090926 PyTorchPredictorContainer.cpp:2413] Failed to execute the method: merge.forward, reason: std::runtime_error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module/___torch_mangle_55.py", line 222, in forward
    _interaction_arch = over_arch._interaction_arch
    _dense_embedding_w = _interaction_arch._dense_embedding_w
    matmul = torch.matmul(mul_3, _dense_embedding_w)
             ~~~~~~~~~~~~ <--- HERE
    main_module13 = self.main_module
    over_arch0 = main_module13.over_arch

Traceback of TorchScript, original code (most recent call last):
  File "<eval_with_key>.1", line 90, in forward
    reshape = getitem_55.reshape(size, -1, 128);  getitem_55 = size = None
    main_module_over_arch__interaction_arch__dense_embedding_w = self.main_module.over_arch._interaction_arch._dense_embedding_w
    matmul = torch.matmul(mul_3, main_module_over_arch__interaction_arch__dense_embedding_w);  main_module_over_arch__interaction_arch__dense_embedding_w = None
             ~~~~~~~~~~~~ <--- HERE
    main_module_over_arch__interaction_arch__dense_embedding_b = self.main_module.over_arch._interaction_arch._dense_embedding_b
    add = matmul + main_module_over_arch__interaction_arch__dense_embedding_b;  matmul = main_module_over_arch__interaction_arch__dense_embedding_b = None
RuntimeError: Cannot set version_counter for inference tensor
E0725 21:17:39.427888 1090926 ModelManagerBase.cpp:896] Model 979134363_89: failed: std::runtime_error: Provided sample inputs are incorrect!
```

After reverting the model
```
I0725 22:21:54.623940 1748217 PyTorchPredictorContainer.cpp:2569] Cannot find TensorRTModuleInfo for method: local.forward
I0725 22:21:54.624598 1748217 PyTorchPredictorContainer.cpp:2339] Loaded sample input successfully for local.forward
W0725 22:21:54.624619 1748217 InferenceContext.h:30] model id is 0_0 by default. Please check.
I0725 22:21:54.624634 1748217 PyTorchPredictorContainer.cpp:2161] Create script predictor for local.forward
I0725 22:21:54.624642 1748217 PyTorchPredictorContainer.cpp:2390] Start to warmup the predictor of the method "local.forward"
I0725 22:21:54.962167 1748217 PyTorchPredictorContainer.cpp:2407] Successfully warmed up the predictor of the method "local.forward" with 10 iteration in 337.535 ms.
I0725 22:21:54.962204 1748217 InferenceContext.h:48] Disabling warm up mode
I0725 22:21:54.962208 1748217 PyTorchPredictorContainer.cpp:2319] Initialize predictor for: remote.forward
I0725 22:21:54.962213 1748217 PyTorchPredictorContainer.cpp:2539] try loading lowered module for method: remote.forward
I0725 22:21:54.962218 1748217 PyTorchPredictorContainer.cpp:2569] Cannot find TensorRTModuleInfo for method: remote.forward
I0725 22:21:54.962514 1748217 PyTorchPredictorContainer.cpp:2339] Loaded sample input successfully for remote.forward
W0725 22:21:54.962541 1748217 InferenceContext.h:30] model id is 0_0 by default. Please check.
I0725 22:21:54.962548 1748217 PyTorchPredictorContainer.cpp:2161] Create script predictor for remote.forward
I0725 22:21:54.962556 1748217 PyTorchPredictorContainer.cpp:2390] Start to warmup the predictor of the method "remote.forward"
I0725 22:21:54.987323 1748217 PyTorchPredictorContainer.cpp:2407] Successfully warmed up the predictor of the method "remote.forward" with 10 iteration in 24.7785 ms.
I0725 22:21:54.987354 1748217 InferenceContext.h:48] Disabling warm up mode
I0725 22:21:54.987360 1748217 PyTorchPredictorContainer.cpp:2319] Initialize predictor for: merge.forward
I0725 22:21:54.987363 1748217 PyTorchPredictorContainer.cpp:2539] try loading lowered module for method: merge.forward
I0725 22:21:54.987368 1748217 PyTorchPredictorContainer.cpp:2569] Cannot find TensorRTModuleInfo for method: merge.forward
I0725 22:21:54.987803 1748217 PyTorchPredictorContainer.cpp:2339] Loaded sample input successfully for merge.forward
W0725 22:21:54.987825 1748217 InferenceContext.h:30] model id is 0_0 by default. Please check.
I0725 22:21:54.987831 1748217 PyTorchPredictorContainer.cpp:2161] Create script predictor for merge.forward
I0725 22:21:54.987838 1748217 PyTorchPredictorContainer.cpp:2375] Keep the sample inputs for method merge.forward
I0725 22:21:54.987843 1748217 PyTorchPredictorContainer.cpp:2390] Start to warmup the predictor of the method "merge.forward"
I0725 22:21:55.163784 1748217 PyTorchPredictorContainer.cpp:2407] Successfully warmed up the predictor of the method "merge.forward" with 10 iteration in 175.951 ms.
I0725 22:21:55.163823 1748217 InferenceContext.h:48] Disabling warm up mode
I0725 22:21:55.232743 1748217 LRMGpuUtils.cpp:967] Start replicating merge to device: cuda:1
I0725 22:21:55.307219 1748217 PyTorchPredictorSetDevice.cpp:25] set_device() method not defined in main module - checking child modules.
I0725 22:21:55.307250 1748217 PyTorchPredictorSetDevice.cpp:29] Calling set_device() for child module: to_device.impl
I0725 22:21:55.481331 1748217 LRMGpuUtils.cpp:977] Warm up replicate merge_1 with merge's sample inputs
I0725 22:21:55.481376 1748217 LRMGpuUtils.cpp:982] Merge module is replicated on device: cuda:1
I0725 22:21:55.481382 1748217 LRMGpuUtils.cpp:987] Reset merge's sample_inputs
I0725 22:21:55.481393 1748217 PyTorchPredictorContainer.cpp:2161] Create script predictor for forward
I0725 22:21:55.526108 1748344 ModelLoadingArbitrator.cpp:106] Load model 979134363_89 with HdfsModelKind = PREDICTION
I0725 22:21:55.530825 1748217 PyTorchPredictorContainer.cpp:2161] Create script predictor for merge_1.forward
I0725 22:21:55.530845 1748217 LRMGpuUtils.cpp:1004] Done with model loading!
I0725 22:21:55.532413 1748217 ModelManagerBase.cpp:884] Loaded 979134363_89 in 57008 ms (17613 ms of IO) memory used 52447080 byte(s)
I0725 22:21:55.532429 1748217 ModelManagerBase.cpp:656]  all models ready in 57 second(s)

```

Reviewed By: frankgt40

Differential Revision: D38142790

fbshipit-source-id: 388b84ef58cbc6161bd4dc25dab291226f682af8