Add debug messages for deps issues during fx splits (#156111)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/156111

Before: {F1979166589}
After: {F1979166595}
The new debug message helped us locate the root cause and make a fix D75686616
Related post: https://fb.workplace.com/groups/vanguard.user.group/permalink/732182419190669/

Test Plan:
- Unit tests: https://www.internalfb.com/intern/testinfra/testconsole/testrun/5066549867107739/

- https://www.internalfb.com/mlhub/pipelines/runs/mast/fire-runming-fm-uih-compression-publish-30_w_pkg
Error message:
```
Exception: Publish failed on rank 0, exception: LoweringExceptionCategory.GENERIC
torch.fx.passes.splitter_base.FxNetSplitterInternalError
[INFRASTRUCTURE_ERROR][GPU_ENABLEMENT] LoweringLogicException: Failed to run local lowering for lowering backend LoweringBackend.AOTINDUCTOR. Exception: Subgraph can't be empty.
Found external node with 0 dependency: preprocessor_group_config
```

Rollback Plan:

Differential Revision: D75636868