Update base for Update on "[MPS] Add support for `MPSDataTypeComplexFloat[16|32]`"
But limit it to MacOS Sonoma +

Before the calling `torch.cat` with complex types failed, but now it works.
Before:
```
% python -c "import torch;print(torch.cat([torch.rand(3, 3, dtype=torch.cfloat).to('mps'), torch.rand(3, 3, dtype=torch.cfloat).to('mps')]))"
TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
```
After:
```
% python -c "import torch;print(torch.cat([torch.rand(3, 3, dtype=torch.cfloat).to('mps'), torch.rand(3, 3, dtype=torch.cfloat).to('mps')]))"
tensor([[0.4857+0.0030j, 0.9375+0.8630j, 0.3544+0.9911j],
        [0.5293+0.8652j, 0.8440+0.1991j, 0.5152+0.8276j],
        [0.0136+0.7469j, 0.1403+0.4761j, 0.2943+0.0896j],
        [0.6458+0.0035j, 0.3579+0.4577j, 0.1723+0.1508j],
        [0.4420+0.3554j, 0.4396+0.7272j, 0.2479+0.1191j],
        [0.3895+0.2292j, 0.7886+0.1613j, 0.9243+0.4180j]], device='mps:0')
```

[ghstack-poisoned]