Update on "[package] issue warning instead of error for dunder imports failures"
When a user has a dependency that uses `__import__` with dynamic arguments, issue a warning and skip the import instead of failing. This PR just wraps the `__import__` logic in a try-catch block. 

```
import torch

with torch.package.PackageExporter("output", verbose=False) as e:
    e.save_source_string('m',  '__import__("these", dont, have, to, be, contants)') # can't resolve dynamic arguments
```
output: 
```
/pytorch/torch/package/find_file_dependencies.py:103: UserWarning: Error importing dynamic __import__ from module 'm', lineno: 1. torch.package does not support dynamic imports. Error encountered: 'Name' object has no attribute 'elts'.
  warnings.warn(
```


[ghstack-poisoned]