[SWDEV-538312] Fix num_stages=8 configs for flex attention (#2277)
num_stages==8 configs are always skipped causing breakages

Example error:
```
torch._inductor.exc.LoweringException: NoValidChoicesError: No choices to select, please consider adding ATEN into max_autotune_gemm_backends config (defined in torch/_inductor/config.py) to allow at least one choice. 
  target: flex_attention_backward
```