Check availability of accelerator in test_schedule (#174760)
The device check contains a fallback if no accelerator is available but doesn't check if one is available and only checks if support is available.

This causes tests to fail with e.g.
> RuntimeError: Found no NVIDIA driver on your system.

Add the `check_avail=True` argument.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/174760
Approved by: https://github.com/Skylion007