Mark underlying type as C10_UNUSED (#80415)
Fixes regression detected in https://github.com/pytorch/pytorch/pull/79978

As result some of the internal workflows fail as follows:
```
aten/src/ATen/native/cpu/CopyKernel.cpp:28:5: error: unused type alias 'underlying_t' [-Werror,-Wunused-local-typedef]
    AT_DISPATCH_QINT_TYPES(dtype, "copy_kernel", [&] {
    ^
src/ATen/native/cpu/CopyKernel.cpp:28:5: error: unused type alias 'underlying_t' [-Werror,-Wunused-local-typedef]
aten/src/ATen/Dispatch.h:393:34: note: expanded from macro 'AT_DISPATCH_QINT_TYPES'
  AT_DISPATCH_SWITCH(TYPE, NAME, AT_DISPATCH_CASE_QINT_TYPES(__VA_ARGS__))
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/80415
Approved by: https://github.com/atalman, https://github.com/peterbell10