Update base for Update on "Testing things in order to get convert working on gpu (WIP)"
Summary: does anyone know why the values created in get_qconv (code in conv.py) are on cuda but the
conv1_input_scale_0 is not?

Test Plan:
python test/test_quantization.py TestQuantizeFx.test_static_gpu_convert

result: 

```
(pytorch) cdhernandez@devgpu108.ash6.facebook.com:/data/users/cdhernandez/pytorch$ python test/test_quantization.py TestQuantizeFx.test_static_gpu_convert
Could not download https://raw.githubusercontent.com/pytorch/test-infra/master/stats/slow-tests.json because of error <urlopen error [Errno 101] Network is unreachable>.
Couldn't download test skip set, leaving all tests enabled...
/data/users/cdhernandez/pytorch/torch/quantization/observer.py:135: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
/data/users/cdhernandez/pytorch/torch/quantization/observer.py:1105: UserWarning: must run observer before calling calculate_qparams.                                    Returning default scale and zero point 
  warnings.warn(
> /data/users/cdhernandez/pytorch/test/quantization/fx/test_quantize_fx.py(1315)test_static_gpu_convert()
-> out = model_quantized(input)
(Pdb) quit
E
======================================================================
ERROR: test_static_gpu_convert (quantization.fx.test_quantize_fx.TestQuantizeFx)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/cdhernandez/pytorch/torch/testing/_internal/common_quantization.py", line 267, in wrapper
    fn(*args, **kwargs)
  File "/data/users/cdhernandez/pytorch/test/quantization/fx/test_quantize_fx.py", line 1315, in test_static_gpu_convert
    out = model_quantized(input)
  File "/data/users/cdhernandez/pytorch/test/quantization/fx/test_quantize_fx.py", line 1315, in test_static_gpu_convert
    out = model_quantized(input)
  File "/home/cdhernandez/local/miniconda3/envs/pytorch/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/cdhernandez/local/miniconda3/envs/pytorch/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

----------------------------------------------------------------------
Ran 1 test in 2.960s

FAILED (errors=1)
```



Reviewers:

Subscribers:

Tasks:

Tags:

still not working

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

[ghstack-poisoned]