unwind: Fix undefined reference to `unwind_c` in `unwind_entry` while LTO is enabled
With LTO enabled, some compiler will optimize it and it will be striped,
which breaks building. Add attribute to avoid this bad situation.

Signed-off-by: GarfieldHan <2652609017@qq.com>