Add remove_duplicate parameter to Module.modules() function (#174383)
#166690 introduced a regression in the `test/test_quantization.py::TestQuantizeFx::test_copy_node_has_shared_actpp_instance` unit test. The test is failing with the following message:
```
FAILED [0.0337s] test/test_quantization.py::TestQuantizeFx::test_copy_node_has_shared_actpp_instance - TypeError: Module.modules() got an unexpected keyword argument 'remove_duplicate'
```

The change of
```
for name, module in m.named_modules(remove_duplicate=False):
```
to
```
for module in m.modules(remove_duplicate=False):
```
introduces a failure because the `modules()` function does not have the `remove_duplicates` parameter.
Considering that `modules()` is a wrapper around and calls `named_modules()`, this PR addresses the failure by adding the `remove_duplicate` parameter to `modules()` the same way as implemented in `named_modules()`. The default behavior still remains the same (removing duplicates by default).
Pull Request resolved: https://github.com/pytorch/pytorch/pull/174383
Approved by: https://github.com/jeffdaily, https://github.com/mikaylagawarecki