Revert "explicit dynamic shapes maps namings (#172405)"
This reverts commit 56f2281c0771c89008f6b81ec5c46e6ef6953679.

Reverted https://github.com/pytorch/pytorch/pull/172405 on behalf of https://github.com/yangw-dev due to sorry but it seems like this breaks internal test, error: AttributeError: 'ShapeEnv' object has no attribute 'var_to_val'. Did you mean: 'val_to_var'? ([comment](https://github.com/pytorch/pytorch/pull/172405#issuecomment-3760701401))