[rocm7.1_internal_testing] fix large tensor sort on ROCm (#2543)
Currently std::min -> ::min did not work as expected on ROCm when input
values >= 2147483648

Replace std::min to ternary statement
Also std::min can be replaced by explicit typing std::min<int64_t>

fixes on ROCm:

test_sort_and_select.py::TestSortAndSelectCUDA::test_sort_large_cuda_float16
error:
RuntimeError: Cannot sort dimension of length 8192

Combines upstream PRs:
- https://github.com/pytorch/pytorch/pull/161054 to fix std::min on ROCm
- https://github.com/pytorch/pytorch/pull/155546 fix python test
- https://github.com/pytorch/pytorch/pull/159939 change test dtype from
int8 to float16

Fixes: SWDEV-526432