xpu: rely on sycl/sycl.hpp to include bfloat16.hpp
Fixes: https://github.com/intel/torch-xpu-ops/issues/1503

`sycl/ext/oneapi/bfloat16.hpp` header file is DPC++ compiler internal header.
It's not documented for usage (see extension specification linked below) and
is not guaranteed to exist. Instead documented usage of extension suggests
to rely on including `sycl/sycl.hpp` which in its turn includes `bfloat16.hpp`
header (which is implementation detail).

We stepped into issues by explicitly including `bloat16.hpp` sycl header
whithin user facing production environment when `intel-sycl-rt` wheel is
installed (which is the dependency of `torch` wheel package built and publicly
available for xpu). Compiler includes this file from `intel-sycl-rt` and
due to `#pragma once` usage its content is included as well giving redefinitions
of symbols in this file (previous inclusion is coming from `sycl/sycl.hpp`):
```
In file included from /workspace/lib/python3.12/site-packages/torch/include/c10/util/BFloat16.h:23:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/ext/oneapi/bfloat16.hpp:60:23: error: redefinition of 'BF16VecToFloatVec'
   60 | template <int N> void BF16VecToFloatVec(const bfloat16 src[N], float dst[N]) {
      |                       ^
/workspace/include/sycl/ext/oneapi/bfloat16.hpp:60:23: note: previous definition is here
   60 | template <int N> void BF16VecToFloatVec(const bfloat16 src[N], float dst[N]) {
      |
```
While SYCL header files themselves can be improved (`#pragma once` dropped), there
is no reason for us to explicitly include sycl `bfloat16.hpp` file either. So,
improving the story on pytorch side this commit drops explicit inclusion of the
named header file.

Further, `SYCL_EXT_ONEAPI_BFLOAT16_MATH_FUNCTIONS` used to cover inclusion of
`sycl/sycl.hpp` does not make sense since it's defined in this very header. Thus,
we should use `SYCL_LANGUAGE_VERSION` instead which is defined on compiler level.

See: https://github.com/intel/llvm/blob/f958dce28053dff145cd725ff57bc4ce94cb94d7/sycl/doc/extensions/experimental/sycl_ext_oneapi_bfloat16_math_functions.asciidoc
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>