[Inductor] Re-run torchgen/fuse/gen_patterns for DistilBert
Summary:
This was failing with the following message:

```
======================================================================
FAIL: test_serialized_patterns_up_to_date (caffe2.test.inductor.test_pattern_matcher.TestPatternMatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/re_cwd/buck-out/v2/gen/fbcode/c31aa23aa97f838b/caffe2/test/inductor/__pattern_matcher__/pattern_matcher#link-tree/caffe2/test/inductor/test_pattern_matcher.py", line 1226, in test_serialized_patterns_up_to_date
    self.assertEqual(
  File "/re_cwd/buck-out/v2/gen/fbcode/c31aa23aa97f838b/caffe2/test/inductor/__pattern_matcher__/pattern_matcher#link-tree/torch/testing/_internal/common_utils.py", line 4089, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: String comparison failed: "eq_S[69 chars]())\nexpand_default = CallFunction(aten.expand[2302 chars]s=0)" != "eq_S[69 chars]())\nview_default = CallFunction(aten.view.def[2379 chars]s=0)"
Diff is 4004 characters long. Set self.maxDiff to None to see it.
Found mismatched pattern _sfdp_pattern_20. Run torchgen/fuse/gen_patterns.py

----------------------------------------------------------------------
```

I'm assuming the code-gen was not up to date or something but this should resolve the error.

Tangentially this was not caught on OSS which was a bit frustrating and attempting to run the files locally produced no output.

```
python3 test/inductor/test_pattern_matcher.py
```

Test Plan:
```
buck test 'fbcode//mode/opt' fbcode//caffe2/test/inductor:pattern_matcher -- --exact 'caffe2/test/inductor:pattern_matcher - test_serialized_patterns_up_to_date (caffe2.test.inductor.test_pattern_matcher.TestPatternMatcher)'
```

Rollback Plan:

Reviewed By: izaitsevfb

Differential Revision: D75827255