add qscheme check for quantization observer (#80126) (#80126)
Summary:
Motivation: each quantization observer only supports a limit qschemes, we need to do this check at the initiation step, rather than at the running step, such as MinMaxObserver with set qscheme with **torch.per_channel_affine**, there will have a runtime error at the running the calibration step:

```
AttributeError: 'MinMaxObserver' object has no attribute 'ch_axis'
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/80126
Approved by: https://github.com/jerryzh168

Test Plan: contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/31f151767b2fde8ba2b73e0fe2b9bd68f284673b

Reviewed By: weiwangmeta

Differential Revision: D39025553

Pulled By: weiwangmeta

fbshipit-source-id: 062bd74b492cfcede91a6a659f92dc68a39806aa