Update base for Update on "[DataPipe] Improving debug message when exceptions are raised within IterDataPipe"
This PR aims to improve the error message coming from `IterDataPipe`. Fixes the "differentiate DataPipe instances" part of https://github.com/pytorch/data/issues/284.

For example, for this code snippet:
```python
from torchdata.datapipes.iter import IterableWrapper, Mapper

def no_op(x):
    return x

def exception_when_one(x):
    if x == 1:
        raise RuntimeError("x cannot equal to 1.")
    return x

map_dp = IterableWrapper(range(10))
map_dp = Mapper(map_dp, no_op)
map_dp = Mapper(map_dp, exception_when_one)
map_dp = Mapper(map_dp, no_op)
print(list(map_dp))
```

Here is the trace prior to this PR. It doesn't clearly state that a DataPipe has encountered an error and which DataPipe is responsible.
```
Traceback (most recent call last):
  File "/Users/ktse/scratch/debugability.py", line 63, in <module>
    print(list(map_dp))
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/_typing.py", line 369, in wrap_generator
    response = gen.send(request)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 110, in __iter__
    for data in self.datapipe:
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/_typing.py", line 369, in wrap_generator
    response = gen.send(request)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 111, in __iter__
    yield self._apply_fn(data)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 76, in _apply_fn
    return self.fn(data)
  File "/Users/ktse/scratch/debugability.py", line 55, in exception_when_one
    raise RuntimeError("x cannot equal to 1.")
RuntimeError: x cannot equal to 1.
```

Here is the trace with this PR. In this version, it more clearly shows that a `MapperIterDataPipe` is throwing the exception and what the input arguments to the DataPipe are:
```
Traceback (most recent call last):
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/_typing.py", line 395, in wrap_generator
    response = gen.send(request)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 111, in __iter__
    yield self._apply_fn(data)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 76, in _apply_fn
    return self.fn(data)
  File "/Users/ktse/scratch/debugability.py", line 55, in exception_when_one
    raise RuntimeError("x cannot equal to 1.")
RuntimeError: x cannot equal to 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ktse/scratch/debugability.py", line 63, in <module>
    print(list(map_dp))
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/_typing.py", line 395, in wrap_generator
    response = gen.send(request)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 110, in __iter__
    for data in self.datapipe:
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/_typing.py", line 406, in wrap_generator
    raise DataPipeException(msg, e) from e
torch.utils.data.datapipes._typing.DataPipeException: thrown by __iter__ of MapperIterDataPipe(datapipe=MapperIterDataPipe, fn=exception_when_one, input_col=NoneType, output_col=NoneType)
```

Improvements to make: make the traceback shorter, such as by skipping over parts related to `response = gen.send(request)` or `for data in self.datapipe`.

[ghstack-poisoned]