[c10d][nvshmem] fix missing override compilation error for nvshmem symmetric code (#159557)
Summary:

Fix error when compiling nvshmem code section `NVSHMEMSymmetricMemory.cu` with BUCK 

```
fbcode/caffe2/torch/csrc/distributed/c10d/symm_mem/NVSHMEMSymmetricMemory.cu:154:20: error: 'get_buffer' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  154 | virtual at::Tensor get_buffer(int 
      |                    ^
fbcode/caffe2/torch/csrc/distributed/c10d/symm_mem/SymmetricMemory.hpp:56:20: note: overridden virtual function is here
   56 | virtual at::Tensor get_buffer(int rank, c10::IntArrayRef sizes, c10::ScalarType dtype, int64_t storage_offset) = 0; 
```

Test Plan:
Build test + CI

Rollback Plan:

Reviewed By: kwen2501

Differential Revision: D78813586