implcit conversion of ::c10d::ReduceOp and ::c10d::ReduceOp::Kind
Build looks okay.

But the test case of PREMUL_SUM is failing

```
======================================================================
ERROR: test_allreduce_ops (__main__.ProcessGroupNCCLTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py",
line 501, in wrapper
    self._join_processes(fn)
  File
"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py",
line 724, in _join_processes
    self._check_return_codes(elapsed_time)
  File
"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py",
line 769, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File
"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py",
line 622, in run_test
    getattr(self, test_name)()
  File
"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py",
line 503, in wrapper
    fn()
  File "/opt/pytorch/pytorch/test/distributed/test_c10d_nccl.py", line
350, in test_allreduce_ops
    allreduce(tensors, c10d.make_nccl_premul_sum(factor))
  File "/opt/pytorch/pytorch/test/distributed/test_c10d_nccl.py", line
317, in allreduce
    work = pg.allreduce(tensors, opts)
RuntimeError: op_ != PREMUL_SUM INTERNAL ASSERT FAILED at
"/opt/pytorch/pytorch/torch/csrc/distributed/c10d/Types.hpp":44, please
report a bug to PyTorch. PREMUL_SUM requires a scale factor tensor or
scalar argument
Exception raised from ReduceOp at
/opt/pytorch/pytorch/torch/csrc/distributed/c10d/Types.hpp:44 (most
recent call first):
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

Try&Error 1. Pass ReduceOp in Ops.cpp

With this change, I'm seeing

```
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch/csrc/distributed/c10d/Ops.cpp:1:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch/csrc/distributed/c10d/Ops.hpp:4:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch/csrc/distributed/c10d/ProcessGroup.hpp:10:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/ATen.h:18:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/TensorIndexing.h:14:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/core/List.h:483:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/core/List_inl.h:4:
In file included from
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/core/ivalue.h:1369:
/home/mkozuki/ghq/github.com/crcrpar/pytorch/aten/src/ATen/core/ivalue_inl.h:1656:59:
error: no type named 'element_type' in 'c10d::ReduceOp'
  using ElemType = typename std::remove_pointer<T>::type::element_type;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

Revert "Try&Error 1. Pass ReduceOp in Ops.cpp"

This reverts commit 2e15955eab248f7a8d81b97c2ef653e4a50d8577.

Add C++ only constructor to ReduceOp to supply supplement

Build is okay

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

cosmetic

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>