[pytorch-vulkan] Add debug utils to vulkan. (#112113)
Summary:
1.  Add operator<< for uvec3
2. show missing `dtype` in `vk_format`


Useful for debugging.

bypass-github-pytorch-ci-checks

Test Plan:
# Test compilation

```
LD_LIBRARY_PATH=third-party/swiftshader/lib/linux-x64/ buck2 run fbcode/mode/dev-nosan    //xplat/caffe2:pt_vulkan_api_test_bin  | pastry
```
Test all pass: P865112285


# Test from another base



```
tstrap.py(58): run_as_main
/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/4e5f7158db62e34c/wearables/camera/ml/pytorch_vulkan_native/__export_emghw_vk__/export_emghw_vk-inplace#link-tree/__par__/meta_only/bootstrap.py(88): run_as_main
/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/4e5f7158db62e34c/wearables/camera/ml/pytorch_vulkan_native/__export_emghw_vk__/export_emghw_vk-inplace#link-tree/__run_lpar_main__.py(32): __invoke_main
/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/4e5f7158db62e34c/wearables/camera/ml/pytorch_vulkan_native/__export_emghw_vk__/export_emghw_vk-inplace#link-tree/__run_lpar_main__.py(70): <module>
RuntimeError: Vulkan vk_format(): no corresponding format for dtype: Long
```

Reviewed By: manuelcandales

Differential Revision: D50676692